### ISSUE TITLE
Wrong status codes on validation errors.

### ISSUE THREAD

**Issue by theTechGuyy** [cloudcreativity/laravel-json-api#103]
When defining a unique rule in validators.attributeRules and the validation fails,
a "JSON API ERROR" with a status code 500 is returned.
A 422 with a proper message seems more appropriate.

Somehow the 422, which is present in the ValidationException, gets lost on the way to returning the error.

Am I right, for this being a bug - or am I missing a piece of the puzzle here?

**Comment by lindyhopchris** [comment]
This would be a bug but you'll have to explain a lot more about the scenario - we have a lot of tests for validation failures in production applications, and the tests are all passing at the moment.

So there's two possible explanations:

1. A different error is occurring after the validation has executed, and that's causing a 500 error to be returned rather than the original validation errors; or
2. All the test cases we have for validation errors don't include something that covers the scenario you've encountered.

Can you log the exception from your exception handler and see where it is originating from? That might help start to work out what is happening.

**Comment by theTechGuyy** [comment]
You're right, should've provided more info - will get back to  you with more details shortly.

**Comment by theTechGuyy** [comment]
Turns out you were right, another package was messing with the reporting..

Sorry to have wasted your time.

**Comment by lindyhopchris** [comment]
Glad it's all resolved.
