### ISSUE TITLE
Add attributes to relationship data

### ISSUE THREAD

**Issue by 1NESLEiN** [cloudcreativity/laravel-json-api#105]
Not sure if [this](https://github.com/neomerx/json-api/issues/179) is possible, or it could be a future enhancement?

I know I would be able to include the relationship, but I would like it like this:
```
"relationships": {
  "author": {
    "data": {
      "type": "people",
      "id": "1",
      "attributes": {...}
    }
  }
}
```
instead of:
```
"relationships": {
  "author": {
    "data": {
      "type": "people",
      "id": "1",
    }
  }
}
...
"included": [
  {...}
]
```
Maybe it is as easy as overriding a function...

**Comment by lindyhopchris** [comment]
Hey! What you are suggesting isn't in line with the JSON API spec. The spec uses sideloading via the "included" top-level member. This is called a "compound document" and is here in the spec:
http://jsonapi.org/format/#document-compound-documents 

The reason I think the spec has rightly gone for this is so that the included resources are only ever added to the document once. If the attributes were serialized in the relationship as you suggest, then because the top-level "data" member could have multiple resources that link to `people:1`, then the `people:1` resource would be serialized multiple times in the document. However, by instead only containing the relationship identifier to `people:1` within the resources in the `data` member, and then including `people:1` in the `included` member, it only gets serialized once.
