### ISSUE TITLE
Non-null boolean values are shown as null when object is created

### ISSUE THREAD

**Issue by danherd** [cloudcreativity/laravel-json-api#107]
The following have been edited for brevity and clarity.

Database:

```
$table->boolean('accommodation')->unsigned()->default(false);
$table->boolean('transport')->unsigned()->default(false);
$table->boolean('weekends')->unsigned()->default(false);
$table->boolean('night_shifts')->unsigned()->default(false);
```

POST:
...
```
"attributes": {
    "accommodation": true
}
...
```

Response (201 Created):

```
...
"attributes": {
    "accommodation": true,
    "transport": null,
    "weekends": null,
    "night-shifts": null
}
...
```

GET:

```
...
"attributes": {
    "accommodation": false,
    "transport": false,
    "weekends": false,
    "night-shifts": false
}
...
```

Surely, the three values that weren't set in the POST should be displayed in the response as 'false' and not null?

**Comment by lindyhopchris** [comment]
This is to do with Eloquent, not the JSON API package. It's getting the value of those attributes from the model, so your model is returning `null` rather than `false`.

This is because the Eloquent model has been saved to the database, rather than retrieved from the database. So those attributes are `null` on the model, even if the database has written them as the default value of `false` (because an Eloquent's models attributes are only populated from the database when retrieving it out of the database).

To ensure you always get booleans, you'll need add the attributes as boolean casts to the `$casts` property on your model.

**Comment by danherd** [comment]
Nice one - thanks!

**Comment by lindyhopchris** [comment]
Actually I have discovered that if the attribute is `null` then the cast still returns `null` (by coincidence discovered this today on something complete unrelated!)

Setting default attribute values in the `$attributes` property will solve it instead.

**Comment by danherd** [comment]
> Setting default attribute values in the $attributes property will solve it instead.

Is that in the hydrator class? How is that formatted?

**Comment by lindyhopchris** [comment]
No, that's on the `Model` class.

**Comment by danherd** [comment]
Ah right - cheers. I've never needed to use that functionality!

**Comment by lindyhopchris** [comment]
I think the only time I've ever used it is for exactly this kind of thing - where I'm having to use values on a newly created Model.
