### ISSUE TITLE
Using wrong content header should give more error information.

### ISSUE THREAD

**Issue by chriscalip** [cloudcreativity/laravel-json-api#111]
Wrong content header attempt.
`
curl -H 'content-type: application/json' -v -X PATCH -d '{"title": "XXX"}' http://cc.demo/api/v1/posts/1 > test2.htm
`
Gives ambigious error message:
`{"errors":[]}`

**Comment by lindyhopchris** [comment]
So the validation here is done by the `neomerx/json-api` package. I haven't previously been able to override the error message it gives for invalid content type, which is why it gives an empty errors message. The HTTP response header is at least correct.

A very recent change to `neomerx/json-api` means however that I can now override this error message, as I requested in this issue:
https://github.com/neomerx/json-api/issues/185

So I now need to update this package to use that change in `neomerx/json-api`.

**Comment by lindyhopchris** [comment]
Closing as fixed on the 1.0 develop branch.
