### ISSUE TITLE
handle model snake_case attributes at CRUD verbs.

### ISSUE THREAD

**Issue by chriscalip** [cloudcreativity/laravel-json-api#117]
Current situation:

If a model has attributes using snake_case (eg. $Term->attribute_a) on GET operations it is
transform into `{ "data": { attributes{'attribute-a": "stuff"} } }` ie. attribute is transform as a hyphenated (dash-case). 

```
curl -H 'content-type: application/vnd.api+json' -X PATCH -v -d '{"data":{"type": "terms", "id": "1","attributes" : {"description": "Content1234", "attribute_a": "XXX"}}}' http://aa.dev/api/v1/terms/1
```
ON Crud operations (PATCH,CREATE) Attributes having dash-case on client-side are **NOT** transform back into backend record model snake_case. 

Still possible to handle on an app-level via `app/JsonApi/Terms/Validators.php method extractAttributes` but it would be nice if this is handled altogether by the package.

**Comment by lindyhopchris** [comment]
Hi. This is possible at the moment, it just isn't automated. Just pass the resource from the response document to your hydrator, along with the model, and the hydrator will take care of all the conversion.

It would be nice to automate this handing off to the hydrator in the future, but I'd have to take a look at where this would sit as it's not in the concern of the client, which is simply for sending a request and receiving a response. The response document always needs to have the response as received, rather than converted, so that you've got access to the "original" document.

**Comment by chriscalip** [comment]
I am not familiar with the codebase yet.
Currently I am doing this via : 
`
    protected function extractAttributes(ResourceObjectInterface $resource, $record = null)
    {
        // $extractor = parent::->extractor;
        // $attributes = ($extractor) ? $extractor($resource, $record) : null;
        $input = $resource->getAttributes()->toArray();
        // Make sure that properties from input that are snake case gets transformed into camel case.
        $known_problems = ['capacitype-code','medicare-code','airs-code'];
        foreach ($input as $key => $value) {
            if (in_array($key, $known_problems)) {
                $camel_case = str_replace('-', '_', $key);
                $record->$camel_case = $value;
            }
        }
        // \Illuminate\Support\Facades\Log::info("Validators extractAttributes", [$resource, $record]);
        return null;
    }
`

**Comment by lindyhopchris** [comment]
`extractAttributes` in the validators is just for extracting attributes for validation. You don't need to convert the case for the validation, as you know the data is hyphen cased - so you can just set your validation rules as `'attribute-a' => 'required|string'`

The validators aren't used in the client at the moment. It might help if you describe what you're trying to do! What's your use case that you are trying to solve by using this package?

**Comment by lindyhopchris** [comment]
For example, attribute rules can use the dasherized form:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.5/app/JsonApi/People/Validators.php#L31

But the Eloquent hydrator takes care of converting them at the time it is going to transfer them into the model - that's the point the case gets converted from dashes to snake case. That's because the validator is for processing the incoming request, whereas the hydrator does conversion - which is why the conversion happens at that point.

**Comment by chriscalip** [comment]
I see handling conversion of dash-case attributes to model snake_case attributes can be handled by both `app/JsonApi/Terms/Hydrator.php method hydrate can achieve app/JsonApi/Terms/Validators.php extractAttributes`

**Comment by lindyhopchris** [comment]
Ok, but you don't *need* to convert the cases in the validator to validate the data. It's wasted effort because the conversion will just run again in the hydrator.

If you do want to do it though, use this in `extractAttributes`:

```php
return $resource->getAttributes()->transformKeys(function ($key) {
   return \CloudCreativity\JsonApi\Utils\Str::underscore($key);
})->toArray();
```

**Comment by chriscalip** [comment]
@lindyhopchris 
Christopher,
I am unable to make proper use of `Validator extractAttributes`


```
    protected function extractAttributes(ResourceObjectInterface $resource, $record = null)
    {
        $attributes = $resource->getAttributes()->transformKeys(function ($key) {
           $output_key = \CloudCreativity\JsonApi\Utils\Str::underscore($key);
           \Illuminate\Support\Facades\Log::info("Validators extractAttributes-closure", [$key, $output_key]);
           return $output_key;
        })->toArray();
        \Illuminate\Support\Facades\Log::info("Validators extractAttributes", [$resource, $attributes, $record]);
        return $attributes;
    }
```

Yields:
```
[2017-10-05 16:41:37] local.INFO: Validators extractAttributes-closure ["description","description"] 
[2017-10-05 16:41:37] local.INFO: Validators extractAttributes-closure ["capacitype-code","capacitype_code"] 
[2017-10-05 16:41:37] local.INFO: Validators extractAttributes ["[object] (CloudCreativity\\JsonApi\\Object\\ResourceObject: {\"type\":\"terms\",\"id\":\"1\",\"attributes\":{\"description\":\"Content1234\",\"capacitype_code\":\"XXXXX\"}})",{"description":"Content1234","capacitype_code":"XXXXX"},"[object] (App\\Term: {\"id\":1,\"name\":\"Mollitia quas esse dolorem adipisci est voluptatem.\",\"description\":\"Content1234\",\"alias\":\"sss-yyyy\",\"capacitype_code\":\"CHUka\",\"medicare_code\":\"11111\",\"airs_code\":\"CHUka\",\"created_at\":\"2017-10-04 20:34:29\",\"updated_at\":\"2017-10-05 16:35:15\",\"deleted_at\":null})"] 
```

But the values from dash-case attributes **DOES NOT** port over to model snake_case attributes.

Just trying to move forward I believe this is doable through other means.. its just not automatically done through the package. 

As such I believe this can be implemented via application code; just not automatically via package.
Thus issue is still active for the moment.

**Comment by lindyhopchris** [comment]
I really don't think this is an issue - otherwise all the tests would be failing and our production applications would be in an awful mess!

`getAttributes()` returns a new instance each time, so you've converted the keys on the instance you got back from that method, but not the attributes on the resource.

The problem here is you are trying to do something that is outside of the remit of the validators. The responsibility for converting keys when transferring data from a resource to a domain record (model in this case) is solely in the hydrator - that is its reason for existing. 

The purpose of the validator is to validate what the client has sent - not convert what the client has sent. So you should be validating the attributes using dasherised keys (as that is what the client has sent).

**Comment by chriscalip** [comment]
`So you should be validating the attributes using dasherised keys (as that is what the client has sent).`
I indeed and I do.

`The responsibility for converting keys when transferring data from a resource to a domain record (model in this case) is solely in the hydrator - that is its reason for existing.`
Fair enough, I will make the adjustments on my app code. Thanks for the info.

`I really don't think this is an issue - otherwise all the tests would be failing and our production applications would be in an awful mess!`
Just reporting of instances where models make use of attributes with snake-cases are not being handled on PATCH|CREATE. It is handled On GET.

**Comment by chriscalip** [comment]
Issue closed. My mistake was on app/JsonApi/Terms/Hydrator.php I added in property `protected $attributes = ['name','description','alias','capacitype_code','medicare_code','airs_code'];
