### ISSUE TITLE
Hydrating pivot relations with additional columns?

### ISSUE THREAD

**Issue by mk-conn** [cloudcreativity/laravel-json-api#122]
I was not able to sync relations where additional pivot columns are used. E.g. I want to set the current authenticated user (fields 'created_by', 'updated_by'). I tried to fiddle around with the hydrateRelated<resource> in the hydrator but did not come any far... Is there some example on how to do this?

**Comment by lindyhopchris** [comment]
Hi @mk-conn 

You can implement a custom method - if your relationship is called "comment", add the `hydrateRelatedComment()` method on your hydrator and it will be invoked instead of the hydrator working out what to do. You'll receive the relationship and the record (model) as the two arguments. The relationship is an instance of `CloudCreativity\JsonApi\Contracts\Object\RelationshipInterface`.

Let me know if this works. It'd also be great if you could share your code as to what you put in the method. The next version is going to have some changes to the hydrator so it'd be really handy if I added a test for what you're doing as I think your use case sounds like its definitely something the package needs to support.

**Comment by mk-conn** [comment]
Okay, I'll try to get something working...

**Comment by lindyhopchris** [comment]
Note to myself. With the new relationship adapters in `1.x-dev`, adding pivot data would be possible.

Something like in the JSON API adapter:

```php
public function comments()
{
    return $this->hasMany()->withPivotData(['foo' => 'bar']);
}
```

(or some other method name)

**Comment by tembra** [comment]
Hello @lindyhopchris 

I read your note to yourself 😆

Now that adding pivot data would be possible, how is the easiest way I can fill these columns by myself while we do not reach 1.1.0 ML? I mean: which function do you suggest to override (if it is even possible with given ones) ?

Another question is how do you pretend to send these pivot data? I'm planing to work with a meta member inside the relationship? What do you think so?

Thank you.

**Comment by lindyhopchris** [comment]
@tembra sorry for slow reply.

Easiest way to do this at the moment is to extend the relationship class - e.g. the `LaravelJsonApi\Eloquent\HasMany` relationship and look at the protected methods in that.

I am not anticipating supporting sending pivot data from the client, because that is not supported by the spec. This feature will be for populating server-side calculated pivot data. If you need the client to supply attributes, you should represent the pivot as a resource in your API. I.e. an intermediary resource between two other resources.

So yes, your Edit 2 is correct!

**Comment by fibis** [comment]
As one of the options is to represent the pivot table as a resource in the API, is there the possibility to add a resource without an Eloquent model but a database table?

**Comment by lindyhopchris** [comment]
Yes this can totally be done! The thing to bear in mind is the encoder maps objects to JSON API schemas using the object class. So you can't just pass in "raw" database results from a query builder.

So you'll need to wrap the row of the pivot database table in a specific class - then map the wrapper class to a JSON API schema in your API's config. This is effectively a *presenter* approach. Let me know if you've got any questions about this.

**Comment by crabmusket** [comment]
It should be possible to do this using a custom controller method too, right? I don't know exactly how to write such a method, but I'll be giving it a go soon.

Also, it looks like Laravel has a [withPivotValue](https://laravel.com/api/5.6/Illuminate/Database/Eloquent/Relations/BelongsToMany.html#method_withPivotValue) method introduced in 5.6 which would allow you to set a 'default' value at the Eloquent level. This looks really handy.

**Comment by lindyhopchris** [comment]
Closing as the new package `laravel-json-api/laravel` has support for pivot tables on belongs-to-many relations:
https://laraveljsonapi.io/docs/1.0/schemas/relationships.html#belongs-to-many

And for filtering using values on the pivot table:
https://laraveljsonapi.io/docs/1.0/schemas/filters.html#wherepivot
