### ISSUE TITLE
Question: Different source of API configuration

### ISSUE THREAD

**Issue by lorenzleutgeb** [cloudcreativity/laravel-json-api#123]
Hi!

I'm using Laravel on top of a custom database architecture. In the database I have all the information needed to generate Adapter, Hydrator, Schema and Validators for all my models. Data is accessible similar using a mechanism similar to Eloquent.

My goal is not to dump auto generated files that can then by picked up by this library but to provide the needed configuration components (listed above) in a programmatic way.

As far as I can see, the only way to configure this library is through configuration files, which are read and transformed in `CloudCreativity\LaravelJsonApi\Repository`. Given my scenario, I would have to change the implementation of this component, which seems doable but not straight forward (it is referenced in the middleware for looking up the API, the service provider and the resource registrar).

An alternative solution would be to extend this library so that I can provide my own `Api` object, and register it with the repository. Would you be open to such a change?

It would also be nice to have an interface instead of `Api` to allow customization.

I am posting here to get a word of advice from you. Have you thought about this use case, and what are your suggested solutions? Thank you.

**Comment by lindyhopchris** [comment]
Hi!

It is totally possible to configure this library for the use case you describe. This is because the Adapter, Hydrator, Schema and Validators classes all implement interfaces. So all you'd need to do is write abstract classes for your particular database setup that implement these interfaces. That is essentially all that has been done for the Eloquent classes that this package provides - each one is just a class that implements the interface.

For example, at work we've got an application that uses Doctrine for some (but not all) of its database storage, so we have written an abstract adapter and hydrator for Doctrine, that are extended for each Doctrine resource.

Hope I've explained that ok - let me know if you've got any questions about what I've written!

**Comment by lorenzleutgeb** [comment]
I am not sure I am following. It is clear to me that these are interfaces, so I can provide a custom implementation. These are the files that [are placed in `app/JsonApi` (and the respective subfolder per resource)](https://github.com/cloudcreativity/demo-laravel-json-api/tree/5.5/app/JsonApi).

However, I would like to not have these files at all. In my case, given a resource name, I would construct a new object that implements Adapter/Hydrator/Schema/Validator *at runtime*.

From what I see, the library is configured by (auto) discovering those files, but it is not clear to me how to configure it dynamically.

**Comment by lindyhopchris** [comment]
Ah, ok - sorry I misunderstood, but it's now clearer! I'll have a think and get back to you...

**Comment by lorenzleutgeb** [comment]
I just (quite late, I know) saw `ResourceProvider` but it seems that this just let's you register another namespace that will be crawled.

**Comment by lorenzleutgeb** [comment]
Ping @lindyhopchris

**Comment by lindyhopchris** [comment]
Hi! Sorry about slow reply. I hadn't actually forgotten about your request and we've actually put in some code to help out with it...

So on the `1.0` dev branch we have the looking up of the class names for the Adapter, Schema etc provided from a `ResolverInterface`. To do your implementation, you'd just need to write your own `ResolverInterface` that returned whatever class name you wanted. I think this will meet your requirements.

The thing I need to add in is a key in the API config file in which you can provide the service container name for your own resolver, so that gets used by the API rather than the default ones provided by this package.
