### ISSUE TITLE
How to use include parameter with generic Adapter ? 

### ISSUE THREAD

**Issue by menthol** [cloudcreativity/laravel-json-api#129]
Il the find function, I can't see anythings to get the parsed include parameter

```php
    /**
     * @param string $resourceId
     * @return object|null
     */
    public function find($resourceId)
    {
        /** @var Entity $entity */
        $entity = $this->getClassName();

        $instance =  $entity::find($resourceId);
        $instance->loadRelationships(???);
        return $instance;
    }
```

**Comment by lindyhopchris** [comment]
Hi! Yes, that's a limitation that we've fixed in the updates for the next version, but unfortunately that version is not ready to use at the moment.

You can however get the parameters the client provided via the `json_api_request()` helper method. Just do this:

```
json_api_request()->getParameters()
```

and you'll get an instance of this:
https://github.com/neomerx/json-api/blob/master/src/Contracts/Encoder/Parameters/EncodingParametersInterface.php

So the include is available on that as `getIncludePaths()`

**Comment by lindyhopchris** [comment]
Or you can just get them via the Laravel `request()` helper.

**Comment by menthol** [comment]
Ok you're right.

Have a second problem.
How to I make the Related resource ou Relationship resource be called in the controller ? Loading the relationship isn't enough to make include work.

the readRelationshipResource and readRelatedResource method are never called in the controller.

**Comment by lindyhopchris** [comment]
@menthol apologies been on holiday and didn't spot your question before going on holiday.

the relationship routes are not fully implemented in the current version. The next version that I'm working on has full support for relationship routes and all related functionality. Hoping to get that version out in the coming few weeks.

**Comment by lindyhopchris** [comment]
Closing this as the questions is related to a really old version. Feel free to open a new issue if there's still a problem.
