### ISSUE TITLE
Filter on relationship/include

### ISSUE THREAD

**Issue by DennisNygren** [cloudcreativity/laravel-json-api#134]
Hi,

Is filtering on a relationship/include supported? I'd like to do something like below but can't seem to get it working:
/api/books?include=details&filter[book_id]=1&filter[details.language]=english

Thanks for a great library!

**Comment by peripteraptos** [comment]
As I see it, it's not supported out of the box and you need to write the filter function by yourself.
I think that is because the JsonApi specification is agnostic about how you use the filter parameter and this could be because the filter parameter can be very unclear. In your situation about whether you want books in english or details in english.

But to implement this, I think I would use a subquery inside of a whereIn function added to the $query object in the filter function of an adapter.php.

Maybe someone has an example for a good implementation?

**Comment by lindyhopchris** [comment]
@DennisNygren sorry, I seem to have missed the email telling me you'd opened this issue.

@peripteraptos is right, this package does not do the filtering for you, it just provides the hook (the `filter` method on the Eloquent adapter) so that you can implement it yourself. This is because the spec is agnostic about how it should be done (so it's not possible for the package to know how to filter), plus the logic for filtering is very specific to each application.

My tip would be to work out how you would write the Eloquent query regardless of JSON API... i.e. forget that you're trying to do it in JSON API and work out how you would write the Eloquent query to do what you're trying to do. Then once you've done that, just incorporate that query into the `filter` method of the JSON API Eloquent adapter.

Feel free to ask any follow up questions!

**Comment by DennisNygren** [comment]
@peripteraptos @lindyhopchris That makes sense, thank you for the explanation!
