### ISSUE TITLE
Method fire does not exist. {"exception":"[object] (BadMethodCallException(code: 0):

### ISSUE THREAD

**Issue by mk-conn** [cloudcreativity/laravel-json-api#138]
This occurs with the latest laravel 5.5.32 when trying to run the generator command.

So I guess... the following should be removed soon? 

AbstractGeneratorCommand::handle
```{php}
/** @todo remove when removing support for Laravel 5.4 */         
if (is_callable(['parent', 'fire'])) {             
return (parent::fire() !== false) ? 0 : 1;       
 }
```

**Comment by lindyhopchris** [comment]
It probably needs the `is_callable` changed to `method_exists` but not sure. It should work, not sure what they've changed in a patch fix to make this suddenly break.

Unfortunately I cannot drop support for Laravel 5.4 until PHP 5.6 is end of life as we have a number of projects where we cannot immediately upgrade to PHP 7.

**Comment by lindyhopchris** [comment]
Confirmed changing it to this works in Laravel 5.5 and 5.4:

```php
if (method_exists($this, 'fire')) {
    return ($this->fire() !== false) ? 0 : 1;
}
```

Caused by this:
https://github.com/illuminate/console/commit/3b064f11996584d9ab866c7d6a4e12944443357e#diff-d14623a39e00e6f07d931705b3ef3d20

A good example of adding a feature in a patch release that then breaks stuff.

Will hopefully be able to do a bug release soon.

**Comment by mk-conn** [comment]
yes... Laravel should follow proper semantic versioning... but thats an old discussion i guess ;)
