### ISSUE TITLE
404 detailed error message

### ISSUE THREAD

**Issue by tooshay** [cloudcreativity/laravel-json-api#146]
I've seen various people ask regarding adding custom exception messages, but I haven't managed to get my head around this. As it stands, a 404 still returns an empty `errors` array (as per spec) in the response body; I did, however, spot the empty `errors` array in the package config, that allows for overriding or adding messages. What I haven't managed to figure out is what the key for that array meant to be? The inline documentation is confusing me.

**Comment by lindyhopchris** [comment]
Hi! I think a limitation of the current version is that you can't override the error for a `404` error. It doesn't pull the 404 error from the array config, which is why it can't be overridden at the moment.

You should be able to do this though, so I'll add it to the `1.0` milestone that we're currently working our way through.

**Comment by tooshay** [comment]
Thanks, Chris!

**Comment by lindyhopchris** [comment]
Closing this as it is current fixed on the 1.0 (develop) branch.
