### ISSUE TITLE
Question: How is the authorizer applied?

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#147]
Hello,
Would you please tell me if the authorizer is applied to a request or to a resource? I mean, will it be fired before serializing included resources or only for the case when it is the main resource? If it applies to both cases, is there a way to distinguish them for the error-handling, i.e. when authorization fails - throw 403, if it is a main resource and if it is a related resource - simply skip inclusion? If it is only for main resources, how could I call manually (if at all) the authorizer of a related resource from within the authorizer of a main resource?
Thank you very much for any suggestions!

**Comment by lindyhopchris** [comment]
Hi!

The authorization is called by the `json-api.authorize` middleware. If you use `php artisan route:list` you can see for your route at what point in the middleware stack this is called.

It is always called on the primary resource's authorizer. So if you have a `posts` resource with a `comments` relationship, the `posts` authorizer will be used for e.g. both the `GET /posts/1` and the `GET /posts/1/comments` requests. I.e. you are authorizing that you can read the comments related to post 1 rather than comments in general.

To access another authorizer you would need to use the Laravel container... e.g. to access the comments authorizer from within the posts authorizer, use:

```
$commentsAuthorizer = app(Comments\Authorizer::class);
```

Does that help? Feel free to ask any follow up questions!

**Comment by dimitvassilev** [comment]
Certainly it does. Thanks a lot for this insight!
