### ISSUE TITLE
Question: How to make a "search" request across multiple parameters?

### ISSUE THREAD

**Issue by santerref** [cloudcreativity/laravel-json-api#150]
Hi all,

First of all, thanks for this package, it is really helpful.

My question is what should be the best approach to make a "search" request across multiple parameters?

Currently, I'm using a custom parameter "*" in my adapter and my validator to search in all my model fields, but I don't know, based on json-api specification, if it's the best way to proceed.

``` php
protected $allowedFilteringParameters = [
        'id',
        'subject',
        '*'
    ];
```

```php       
 if ($filters->has('*')) {
            $query->where('id', 'like', '%' . $filters->get('*') . '%')->orWhere('tasks.subject', 'like', '%' . $filters->get('*') . '%');
        }
```

The problem is if I use the id and the subject filters, this will make an AND condition, not an OR.

My code works, I'm looking for a better way to do it (if there is one).

Thanks!

**Comment by lindyhopchris** [comment]
Hi! The spec doesn't specify anything about how filters should be implemented, just that they should be contained within the `filter` query parameter. This is because filters are very application specific, so it makes sense for each application to be given the freedom to implement them as it sees fit.

In your case, your `*` filter makes sense for a search on any fields, but it wouldn't make sense to apply any other fitlers if that one is sent by the client. So in your `filter` method you may want to do:

```php
if ($filters->has('*')) {
  // do search query
} else {
  // do other filtering
}
```
