### ISSUE TITLE
Generate Adapter command leads to namespace conflict

### ISSUE THREAD

**Issue by Wizofgoz** [cloudcreativity/laravel-json-api#176]
Sorry, just found another problem with the generator command when by-resource is false.

When a new adapter is generated for a model, the following is the result (using a Post model as an example):
- namespace use statement is added with `App\Post`
- adapter class is named `Post`
- model passed to parent constructor is `new Post()`

This creates a naming conflict on the namespace where the model and adapter have the same name.

To fix this, I propose either adding an alias to the namespace use statement (and changing name of model used when calling parent constructor) or remove the use statement and use the FQCN of the model.

**Comment by fisharebest** [comment]
In https://github.com/cloudcreativity/laravel-json-api/issues/100 you said that the package had support for class names such as `PostAdapter`, `PostHydrator`, `PostValidator`, etc. - but it needed exposing/documenting.

Such a structure would solve this problem.

**Comment by lindyhopchris** [comment]
@Wizofgoz yeah had realised this would clash. My preference is definitely for removing the use statement and use the FQCN of the Model in the constructor. Are you able to do a PR to the `develop` branch?

@fisharebest I could potentially add an extra config setting to allow `PostAdapter` etc but I can't now make that the default for `by-resource` as `false` because it would break all the apps that have been using `by-resource` as `false`. So I'd have to continue using the current implementation anyway and we'd need to solve this use by removing the use statement anyway.

Is supporting `PostAdapter` etc something you'd like added?

**Comment by fisharebest** [comment]
> Is supporting `PostAdapter` etc something you'd like added?

IMHO, the `ModelType` naming convention is much easier to read and more consistent.

This is especially true when writing example code and documentation.

Laravel uses this structure by default.  e.g. `Requests\PostRequest`, `Notifications\PostNotification`, `Factories\PostFactory`, etc.

This package already uses it for `Controllers\Api\PostController`.

**Comment by lindyhopchris** [comment]
@fisharebest you make a really good point. I'll change the default behaviour for `by-resource:false` to match `ModelType` but provide a way for people who have followed the old convention to still use that without having to rename all their classes.

**Comment by lindyhopchris** [comment]
Pushed two fixes to for this to the `develop` branch, which will be the `1.0.0-alpha.3` tag.

Firstly in the Eloquent stub, the model class is no longer imported so that solves collisions with the adapter class name.

Secondly, the default *not-by-resource* behaviour is to append the type to the classname, i.e.:
`App\JsonApi\Adapter\PostAdapter` instead of `App\JsonApi\Adapter\Post`. However, so that people don't need to rename their classes immediately, they can set their `by-resource` option to the string `false-0.x` to maintain the old behaviour.
