### ISSUE TITLE
Using UUID instead of ID

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#183]
Hi,
I am having trouble with specifying that the 'id' field of the resource should be a different attribute, namely 'uuid'. I have both an 'id' attribute on my model, which is the primary key, and an 'uuid' attribute which I would like to be the public identifier of the resource, i.e. use it in the routes, resource links and as the 'id' field. Not having specified the ` protected $primaryKey = 'uuid'; ` in the adapter, I can sucessfully fetch from both the index and read (using the 'id') endpoints of the resource (using the default controller), however setting it has no effect on the encoded resources fetched via the index endpoint ('id' of the resource is still the 'id' model attribute and links use it), makes the read endpoint via 'id' invalid (as expected) but it doesn't work via the 'uuid' value in the url, either. 
I tried with returning the 'uuid' from the getId() method in the schema - this correctly assigns it to the 'id' field of the resource and is used for the links generation, however the read endpoint still doesn't work.

I am wondering if it is at all possible to use an attribute other than the primary key as an identifier, if I am missing something in the way the schema and adapter are configured or if it is not supposed to behave like this?

As always, thanks a lot for your help!

Edit: P.S. I am using the 1.0.0-alpha.2 version.

**Comment by lindyhopchris** [comment]
Hi!

Thanks for reporting, I was under the impression that this is working but should add some tests to double check. You'd definitely need to set both the `$primaryKey` to `uuid` on the adapter and return the `$model->uuid` from the schema's `getId()` method.

There's no test cases for this scenario but there should be, so I'll see if I can get this working in the tests.

**Comment by fisharebest** [comment]
FYI - this is working for us (on 1.0.0-alpha.2).

We simply set `$primaryKey` and `function getId()` as described above.

Looking at our code, the only things we've done to implement UUIDs are

* We added a `Model::creating()` function to our eloquent models to set a UUID when creating new entities.
* We set `Model::getRouteKeyName()` to return 'uuid' because we have a few routes that don't go via the API.

**Comment by lindyhopchris** [comment]
I can't replicate this in tests either - tests running on `1.0.0-alpha.3`. The commit above shows what we had to do to get it working.

@dimitvassilev  Any chance there's anything different you're doing in your adapter, schema or model class than we're doing in that commit?

**Comment by fisharebest** [comment]
> maybe we should be using `getRouteKeyName()` as the default rather than `getKeyName()`

Since these are generally used as the "external" and "internal" identifiers of a record, it makes sense that the API would use the "external" one by default.

**Comment by lindyhopchris** [comment]
@dimitvassilev no problem, always good to add an extra scenario to the test cases!

@fisharebest that's what I was thinking too. the next release is `1.0.0-beta.1` so I'll change it for that. (there's only going to be 1 or 2 betas so good to get this in before 1.0 as it'll be a breaking change.)

**Comment by tsampy** [comment]
Hi. I have troubles with the id.
We use ID in our DB as primaryKey.
So I set the adapter's $primaryKey to 'ID' and the schema's getId() method returns $resource->ID.

I can get the list of records, but when I wanna access a record, I get a 404 error.
I.e, if I wanna access the record with ID 1, I get a "Resource <resourceName> with id 1 does not exist." message.

I included a error_log in the getId() method.
And I only get a error log when I try to get the list, not to access a single record.
So it seems that getId() is not called when accessing a single record.

How can I change the ID ?

**Comment by lindyhopchris** [comment]
Did you figure this out? Can't see your comment any more on the issue.

**Comment by tsampy** [comment]
Yes, I deleted my comment, just because it was an obvious mistake from me.
I've just forgotten to implement the adapter's find() method.
Shame on me 🙂

Thiéry SAMPY
________________________________
De : Christopher Gammie <notifications@github.com>
Envoyé : lundi 19 août 2019 15:34
À : cloudcreativity/laravel-json-api <laravel-json-api@noreply.github.com>
Cc : Thiéry SAMPY <tsampy@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [cloudcreativity/laravel-json-api] Using UUID instead of ID (#183)

Did you figure this out? Can't see your comment any more on the issue.
