### ISSUE TITLE
JsonApiController's creating hook should receive model instance again

### ISSUE THREAD

**Issue by jelhan** [cloudcreativity/laravel-json-api#186]
Before https://github.com/cloudcreativity/laravel-json-api/commit/6b72c274eb6033cce187b2d2cc22f081aa040115#diff-2404f25e8d2fcef688d8a092d28a9e17 `creating()` hook of `JsonApiController` got an instance of the model being created. This allowed us to modify the record before it's created. After the change `creating()` only gets a `ResourceObjectInterface`. This was released in `v1.0.0-alpha1` and makes modifying the record being created much more difficult.

As shown in the demo app and explained in #178 we could override `createRecord()` method of the Adapter to achieve something similar. But is it really a good idea to move business logic from Controller to Adapter? This might be okay, if it's only about associating the author to a post, but I have use cases where I have to do complex calculations, creating other records or even assets before storing the record. Moving this to `created()` hook is not an option. Not only because it wouldn't be a good performance wise to persist the record twice but also because of database constraints.

**Comment by lindyhopchris** [comment]
Hey! Thanks for raising this issue.

We moved the creating the instance of a record into the adapter, because the adapter's purpose is to creating, read, update and delete records, so makes sense as a single unit for all CRUD rather RUD being in the adapter and C being in the controller!

> But is it really a good idea to move business logic from Controller to Adapter?

As a general rule we don't put any business logic in controllers, as that means the business logic is confined to a controller rather than being available for anything in the application that needs it. Our controllers tend to always receive a validated request and hand off to something else that does the business logic (e.g. a service) before returning a response.

Like you we do have scenarios where creating a record is more complex than just filling an Eloquent model. Where this is the case, we tend to encapsulate this logic in a service (so that it is re-usable anywhere in our application that needs it), and then the JSON API adapter just hands off to this service instead of creating an Eloquent model directly.

To do this you would overload the public `create` method on the adapter. I.e. the following is a rough pattern of what we might do:

```php
<?php

namespace App\JsonApi\Posts;

use App\Post;
use App\Services\PostService;
use CloudCreativity\LaravelJsonApi\Contracts\Object\ResourceObjectInterface;
use CloudCreativity\LaravelJsonApi\Eloquent\AbstractAdapter;
use CloudCreativity\LaravelJsonApi\Utils\Arr;
use Neomerx\JsonApi\Contracts\Encoder\Parameters\EncodingParametersInterface;

class Adapter extends AbstractAdapter
{

    private $service;

    public function __construct(PostService $service)
    {
        parent::__construct(new Post());
        $this->service = $service;
    }

    public function create(
        ResourceObjectInterface $resource, 
        EncodingParametersInterface $parameters
    ) {
        $values = Arr::underscore($resource->getAttributes()->toArray());

        // do any other conversion to get the values into the format
        // expected by the service.

        return $this->service->createPost($values);
    }

    // ...

}
```

Alternatively, if you want the adapter to do everything except save the new model (because the business logic service needs to do that), then you can overload the `persist` method:

```php
<?php

namespace App\JsonApi\Posts;

use App\Post;
use App\Services\PostService;
use CloudCreativity\LaravelJsonApi\Eloquent\AbstractAdapter;

class Adapter extends AbstractAdapter
{

    private $service;

    public function __construct(PostService $service)
    {
        parent::__construct(new Post());
        $this->service = $service;
    }

    protected function persist($record)
    {
        if (!$record->exists) {
            return $this->service->createPost($record);
        }
        
        return parent::persist($record);
    }

}
```

There are two other alternatives... 

- If your logic should be running *every* time one of those models is created, you should definitely be using the Eloquent `creating` hook instead.
- If you definitely want to keep the logic in the controller then you can overload the `create` method on the controller.

Let me know whether any of these approaches work for you... would be good to know so that I can add some guidance to the docs.

**Comment by jelhan** [comment]
Hello Christopher, thanks for this quick and detailed answer. Really appreciate!

If i got you right, `creating` and `updating` hooks of `JsonApiController` are only meant for validating request but not for modification of the data aren't they? Would be good to clear that out in docs.

I see your points about application architecture and the benefits of moving this kind of logic outside of controller and adapter. Seems like a approach if Model hooks aren't an option.

By the way: Thank you very much for this great package!

**Comment by lindyhopchris** [comment]
As of `1.0.0-beta.6` there are now hooks in the adapter. The `creating` hook in the adapter receives the model that will be created.

Closing this issue as I believe those new hooks mean it is no longer relevant.
