### ISSUE TITLE
Question: Handling Roles and display attributes on role level

### ISSUE THREAD

**Issue by svparijs** [cloudcreativity/laravel-json-api#191]
Hi there,

We are currently working on a JsonApi implementation with several permission layers. We want to be able to:

1. Show records based on permissions
2. Show attributes based on permissions
3. Show related resource attribute based on permissions

We haven't found any example code for these use cases. This is a pretty important feature for us, would you be able to provide an example or guidance which place in the architecture is suited of this kind of logic?

**Comment by lindyhopchris** [comment]
Hi!

Here's some ideas as to how this can be implemented.

## Show records based on permissions

When reading a specific record, `e.g. GET /api/posts/1`, you should use authorization to determine whether or not the user can read the record:
http://laravel-json-api.readthedocs.io/en/latest/basics/security/

That chapter gives a number of approaches, personally I tend to prefer using the `Authorizer` classes as I like having a specific unit dealing with the authorization logic.

You'd also need to scope your adapter so that it only ever returns records that the user has permission to see, e.g. when filtering records. You can do this in the filter method, e.g.:

```php
protected function filter($query, Collection $filters)
{
  if (Gate::denies('my-role')) {
    $query->where('table.my_column', '<>', 'foo');
  }

  // apply filters
}
```

> The adapter also allows a filter by id approach, so you'd also need to overload the `findByIds` method to modify the query there as well.

## Show attributes based on permissions

You can decide what to return as attributes in your schema:

```php
public function getAttributes($resource)
{
  $attrs = ['foo' => $resource->foo, 'bar' => $resource->bar];

  if (Gate::allows('my-role')) {
    $attrs['baz'] = $resource->baz;
  }

  return $attrs;
}
```

## Show related resource attribute based on permissions

Just use the same approach to decide what attributes to serialize within the schema of the related resource.

## Modify resource attributes based on permissions

Something else you should factor in is what attributes the user is allowed to fill when updating a resource (if this is going to vary based on permissions).

In your adapter, overload the `getFillable` method:

```php
protected function getFillable($record)
{
  $fields = ['foo', 'foo-bar'];

  if (Gate::allows('my-role')) {
   array_push($fields, 'baz', 'baz-bat');
  }

  return $fields;
}
```

It's worth noting that the schema and the adapter are created via the Laravel container so you can use constructor injection if you prefer that to using facades.

Let me know if this helps give you some ideas!

**Comment by svparijs** [comment]
Hi @lindyhopchris thanks for your reply! Every useful indeed.

Initially I had a similar approach this did not work(at first probably a mistake on my part). Now we have something similar to your suggestions. The API is well thought through so thank you for your efforts!

**Comment by lindyhopchris** [comment]
Great, glad to hear.

One thing to bear in mind is if you are calling something like `Gate::allows`, I'm not sure how efficient that is if making lots of calls to it... because I think Laravel probably assumes you're only going to call it once per request.

If it's not very efficient then constant calls to it in your schema will massively slow down encoding, particularly if you're encoding lots of resources (e.g. when filtering resources).

So you might want to check the permissions via a service that caches the answer the first time it gets checked.

**Comment by svparijs** [comment]
@lindyhopchris Thanks for the suggestions. We especially like Validations.php implementation and extensive documentation a huge plus!

**Comment by lindyhopchris** [comment]
Great, glad you like the implementation!
