### ISSUE TITLE
Support for Elastic Search

### ISSUE THREAD

**Issue by GIANTCRAB** [cloudcreativity/laravel-json-api#200]
Was wondering if there's anyway I could use third party tools for elastic search in the 'filter()' method?

Thanks!

**Comment by lindyhopchris** [comment]
Well you can do whatever you want in the filter method! I haven't used elastic search, so not sure what you'd need to do.

If the `filter` method doesn't work for it because you don't need an Eloquent query builder that it takes as its argument, you can overload the `query` method instead. The `filter` method is just one part of the generic implementation that is in the `query` method:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Eloquent/AbstractAdapter.php#L153

Your other option is to write your own custom adapter for it:
http://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#custom-adapters

**Comment by lindyhopchris** [comment]
Closing this as I think I've answered the question. Feel free to re-open if needed!
