### ISSUE TITLE
Unable to make TrimString middleware work

### ISSUE THREAD

**Issue by germikee** [cloudcreativity/laravel-json-api#201]
```
<?php

namespace Illuminate\Foundation\Http\Middleware;

use Closure;
use CloudCreativity\JsonApi\Contracts\Http\Requests\RequestInterface;
use Symfony\Component\HttpFoundation\ParameterBag;

class TransformsRequest
{
    /**
     * The additional attributes passed to the middleware.
     *
     * @var array
     */
    protected $attributes = [];

    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  array  ...$attributes
     * @return mixed
     */
    public function handle($request, Closure $next, ...$attributes)
    {
        $this->attributes = $attributes;

        $this->clean($request);

        return $next($request);
    }
...
```

Request trims successful but using the `Dingo\Api\Http\Request`. How can I use trim request used by this package?

**Comment by germikee** [comment]
Tried using this `app(CloudCreativity\JsonApi\Contracts\Http\Requests\RequestInterface::class)` but throws binding resolve exception

**Comment by lindyhopchris** [comment]
Hi!

So thanks for pointing this out as it hadn't previously occurred to me that string trimming would not be working.

The reason it's not working is because this package is built on top of a framework agnostic package: `neomerx/json-api`. As that is framework agnostic, it uses the PSR `ServerRequestInterface` in several places. As a result we're getting the HTTP request body (JSON) from the server request, rather than the Illuminate request - but the trim strings middleware runs on the Illuminate request.

The other problem we have is that we need the JSON body as an object, not an assoc array to validate it against the spec. This is because there is a semantic difference in JSON between the client sending something as an object or an array - and if we decode as an assoc array, we can't tell whether the client sent something in the body as an object or an array as both are decoded as an array. The trim strings middleware runs against the JSON as an array, not an object, because the Illuminate request's `json` method returns an array, not an object.

I think the solution to this is to validate the request body against the spec as an object, but once that passes, uses the Illuminate request's `json` method for everything else... i.e. for validation and creating/updating records. This would mean that the trim strings middleware will then have an effect. I would need to make this change when working on the validation upgrades that I have planned.

As a side-note, the JSON API request interface is only bound into the service container within JSON API routes - i.e. after the `json-api` middleware has run.

**Comment by lksnmnn** [comment]
I believe changing this will also make the `ConvertEmptyStringsToNull` middleware work.

**Comment by johannesschobel** [comment]
has this been fixed in 1.0.0-beta?

**Comment by lindyhopchris** [comment]
Not yet, but it will be fixed during the beta cycle.

**Comment by johannesschobel** [comment]
thanks a lot for your time!
