### ISSUE TITLE
Eager load the $defaultWith of included models

### ISSUE THREAD

**Issue by calvinps** [cloudcreativity/laravel-json-api#210]
Is there a way to have `$defaultWith` relationships of included models eager loaded in the initial query too? As a simple example, say there is a "Customer" model that belongs to a "User" model and the "User" model belongs to a "City" and to an "Organization". On the User's Schema, the city and organization relationships are defined and always "show data." To make a `/users` request load faster, the User's Adapter has `$defaultWith = ['city','organization']` so that those relationships can be eager loaded. 

What I'm observing, however, is that if I make a request to `/customers?include=user` then the `user` relationship of the customer is eager loaded, but not `user.city` or `user.organization`. Thus, the request takes a long time to complete as each included user has it's city and organization loaded from the database one by one. 

Is there a way to achieve the eager loading of the included model AND it's $defaultWith on this initial request? Using the above example that would mean a request to  `/customers?include=user` would generate a "with" query of `['user','user.city','user.organization']` and not just `['user']` as I'm currently observing. 

I imagine this is pretty common scenario so hopefully I'm just missing something basic. If you can point me in the right direction on how to achieve this kind of eager loading that would be great. Thanks!

**Comment by lindyhopchris** [comment]
Hi!

The `$defaultWith` is definitely already merged with the include paths, at this line:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/Concerns/IncludesModels.php#L76

However that will be on the adapter that is handling the request. So for

`/customers?include=user`

Your `customers` adapter is handling the request, so it's merging the default with for the customers, not the user's adapter. This is because if I started iterating over all the adapters to pull out all the default with paths, it would firstly be very costly and secondly I'd need to know how every single Eloquent relationship that I could encounter maps back to JSON API resource relationships. Which would be do-able, but as I said, would be costly.

What you actually need to do here is configure your `customers` adapter so that if `users` is in the include path, it translates this to model paths of `users.city` *and* `users.organization`. At the moment the adapter allows you to define mapping paths on the `$includePaths` property as per the docblock here:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Eloquent/Concerns/IncludesModels.php#L33-L62

I think it would be great to add to that by being able to do this on your `customers` adapter:

```php
protected $includePaths = [
  'user' => ['user.city', 'user.organization']
];
```

I.e. map the single JSON API include path of `user` to multiple Eloquent eager load paths.

Let me know what you think...

**Comment by calvinps** [comment]
Thanks for the quick reply! I tried it out and it seems like a viable solution, although one issue came up when trying to include a nested array in $defaultWith. The [convertIncludePaths function](https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/Concerns/IncludesModels.php#L85-L90) returns a nested array similar to the following:
```
[
  'someModel',
  [
    'user.city',
    'user.organization'
  ]
]
```

 that ends up causing an error down the line in the eloquent query builder. 

Adding `flatten()` to `function convertIncludePaths($includePaths)` fixed it, like so:

```
    /**
     * @param Collection|array $includePaths
     * @return Collection
     */
    protected function convertIncludePaths($includePaths)
    {
        return collect($includePaths)->map(function ($path) {
            return $this->convertIncludePath($path);
        })->filter()->values();
    }

// returns ['someModel','user.city','user.organization']
```

If you're OK with adding in the flatten function or otherwise fixing the bug that comes up with nested arrays then I will definitely use your proposed solution.

**Comment by lindyhopchris** [comment]
That looks like a good solution. Are you able to submit a PR to the `develop` branch with the `flatten` change?

**Comment by lindyhopchris** [comment]
Thanks for the PR. This will be in the `1.0.0-beta.1` release. Not sure when I'll have time to sort that out, but if you want to use it in the meantime just require the develop branch:

```bash
$ composer require cloudcreativity/laravel-json-api:^1.0
```

Making sure you've got these settings in your composer JSON:
https://github.com/laravel/laravel/blob/master/composer.json#L57-L58

There's a only a few upgrade notes for `1.0.0-beta.1` so far:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/upgrade.md#100-alpha3-to-100-beta1
