### ISSUE TITLE
Question: Sorting based on relationship value?

### ISSUE THREAD

**Issue by svparijs** [cloudcreativity/laravel-json-api#212]
Currently we have a server-side paginated grid which can be sorted and filtered upon. We use related attributes inside the grid like Vendor name. Is there a _best-practice_ way to sort the resource based on this relationship value? 

We currently have a implementation where we `leftJoin` a relation inside the filter. Then overwrite the `columnForField` with this code:

```
    /**
     * Get the table column to use for the specified search field.
     *
     * @param string $field
     * @param Model $model
     * @return string
     */
    protected function columnForField($field, Model $model)
    {
        /** If there is a custom mapping, return that */
        if (isset($this->sortColumns[$field])) {
            return $this->sortColumns[$field];
        }

        if (\strpos($field, '.')) {
            $relation = \strtok($field, '.');

            if (\method_exists($model, $relation)) {
                /** @var Relations\Relation $relationShip */
                $relationShip = $model->$relation();
                $table = $relationShip->getRelated()->getTable();

                if (($position = strpos($field, '.')) !== false) {
                    $tableWithField = $table . substr($field, $position);
                    return $model::$snakeAttributes ? Str::underscore($tableWithField) : Str::camelize($tableWithField);
                }
            }
        }

        return $model::$snakeAttributes ? Str::underscore($field) : Str::camelize($field);
    }

```

This implementation only works if you have set the `$table` variable of the model and of a first level relationship.

**Comment by lindyhopchris** [comment]
Hi!

The simplest way would be to use the sort mapping that you can add to the `sortColumns` property on your adapter:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Eloquent/AbstractAdapter.php#L100-L109

E.g. map the JSON API sort field `foo` to `foo.bar`:

```
protected $sortColumns = [
  'foo' => 'foo.bar',
];
```

You can add as many of these mappings as you need, and you might find this easier to maintain. However, if it doesn't really meet your requirements then overloading one of the methods is definitely the way to go. Either the one you've chosen or I'd go for `sortBy` or `sort` itself.

I've split stuff out into different methods to give people the opportunity to overload different bits of the adapter logic, because it's never going to be possible to write an abstraction layer that can deal with complex use cases like yours.

Not sure how much that helps but hopefully it does. Do let me know if you had any suggestions that would make it easier to plug in what you're trying to do.

**Comment by svparijs** [comment]
Hi @lindyhopchris thanks for the reply.

I'd expected the nested notations to work "just" work. This is how other PHP frameworks I used would handle this. Unfortunately Eloquent does this differently and its not really a JSON-API issue.

When we extend the use of the sorting, we might come up with a "better" implementation for now we use what I created.

**Comment by lindyhopchris** [comment]
No problem. I'll close this issue for now but feel free to create a new issue if you come up with a solution that would be good to add to this package.
