### ISSUE TITLE
Question: Config for "per package" api

### ISSUE THREAD

**Issue by janata-jan** [cloudcreativity/laravel-json-api#216]
Hi! Awesome package.

I'm trying to distribute resources/adapters/schemas,... etc in different laravel packages (as per scope of my application). Everything seems to work just fine, but (there is always some "but") the resource/adapter/... generator seems to put new files in /app folder no matter what I do.

Example setup:
1. package is in folder: /vendor/javi/api-base,
2. package's config.json includes proper path for psr-4 autoloader,
3. package's service provider loads config properly (tested), also calls `JsonApi::defaultApi('v1');`,
4. config has right namespace based on config.json - as in para 2.,
5. if I put generated resource files from /app/Javi/api-base/... to package folder (/vendor/javi/api-base/...), it works like a charm.

The only thing which does not work for me, are console commands used to generate resources - for example, calling `artisan make:json-api:resource users v1` puts resource files into /app/Javi/api-base/... It should be in /vendor/Javi/api-base/... (where the namespace has its source according to config.json - para 2.)

I know the config uses Laravel's `Application::getNamespace()` to determine the the root namespace...

**Comment by lindyhopchris** [comment]
Hi! Glad you like the package.

My question for this is do *any* of the Laravel generators work in generating things in the vendor directory? If they do then this is clearly something that this package should also support, but if they don't I'm not sure it's worth adding in the extra complexity.

As far as I'm aware Laravel dropped the idea of developing packages in the vendor directory some time ago. Personally this is a development approach I've never taken - I do package development separately and fully test stuff within the package before pulling it into an application, rather than dev'ing in the vendor folder. `orchestra/testbench` is really useful for that.

I suppose what I'm saying is the generators are only really meant to work like the other Laravel generators, if they don't support generating stuff in the vendor folder then I probably wouldn't put this as something I'd want to spend the time adding in when there's lots of other `1.0` stuff for me to work on at the moment! Hope that makes sense!

**Comment by janata-jan** [comment]
Thanks for fast reply.

I really enjoy this package, and consider your approach to be just fine - no need to add any new functionality / complexity that is not really that useful. I was asking mainly to know, if I am doing it right / not making some mistake.

Once again - thank you for your hard work and for delivering such useful package.

**Comment by lindyhopchris** [comment]
Ok, great thanks for confirming and thanks for the encouraging feedback!
