### ISSUE TITLE
Question: Programatically included related resources

### ISSUE THREAD

**Issue by fisharebest** [cloudcreativity/laravel-json-api#228]
The schema documentation has the following example:

```
class Schema extends SchemaProvider
{
    public function getRelationships($post, $isPrimary, array $includeRelationships)
    {
        return [
            'author' => [
                self::SHOW_DATA => isset($includeRelationships['author']),
                self::DATA => function () use ($post) {
                    return $post->createdBy;
                },
            ],
        ];
    }
}
```

Suppose I wanted to force the author to be included always.
I could  set the `SHOW_DATA` parameter to `true`.  e.g. 

```
class Schema extends SchemaProvider
{
    public function getRelationships($post, $isPrimary, array $includeRelationships)
    {
        return [
            'author' => [
                self::SHOW_DATA => true,
                self::DATA => function () use ($post) {
                    return $post->createdBy;
                },
            ],
        ];
    }
}
```

This does indeed add the author relationship to the post (but not the author object).

Is there a way to (programmatically) cause the related author to be included?

**Comment by lindyhopchris** [comment]
Hi! The author will only be in the `included` part of the response document if the client has asked for it to be included.

However, the neomerx package (the does the encoding) allows you to specify the default include paths if the client has not provided any. You can do that by implementing the `getIncludePaths` on you schema:

```php
public function getIncludePaths()
{
    return ['author'];
}
```

These are only used when the client has not specified any include paths. I.e. if the client sends include paths and doesn't have the author in those paths, then the author will not be included. This is the desired outcome though because if the client isn't asking for the author to be included, then it's right to omit it.

This is documented here:
https://laravel-json-api.readthedocs.io/en/latest/fetching/inclusion/

**Comment by fisharebest** [comment]
> will only be in the included part of the response document if the client has asked for it

The JSON API spec says this about related resources:

> An endpoint MAY return resources related to the primary data by default.
> An endpoint MAY also support an include request parameter to allow the client to customize which related resources should be returned.

The first point says that the server can include it, without being asked.  This is what I'm trying to achieve.

**Comment by fisharebest** [comment]
OK, I get it.  We can include either the client's list of included resources or the server's list of included resources, but not merge the two.

**Comment by lindyhopchris** [comment]
Yes that's correct. If we wanted to merge the two, that'd be something we'd need to raise as an issue in the `neomerx/json-api` package.

**Comment by lindyhopchris** [comment]
To be honest I can't see a scenario where you would want to merge the server's list with the client's list. The reason being is the whole spec is designed around letting the client control what it wants (because it knows what it is doing with the data), so if the client provides a list of what it wants included it makes more sense to just go with that list rather than merging paths into it.

**Comment by fisharebest** [comment]
> I can't see a scenario where you would want to merge the server's list with the client's list

My user object has many related objects (avatar image, etc.).  Every client request for a user will always want all of these related objects.

If I request a post, its comments, and the replies to the comments - and I want the author of all three entities to be included, I have

`GET:/api/posts/123?include=author,comments.author,comments.replies.author`

Now, if each of the `author` relations also needs to specify several of its own relations , then the size of the include parameter grows exponentially.

Then, adding a new relation to the author (perhaps "badges"), means that lots of API calls in the client need lots of changes, which is proving to be time-consuming and error prone.

**Comment by fisharebest** [comment]
I guess we can always have some client-side code to rewrite the `include` parameter to include all the user-relations.

I was asked to investigate automating it on the server side....

Don't waste any more of your time on this.
