### ISSUE TITLE
Validation Relationship rules 

### ISSUE THREAD

**Issue by svparijs** [cloudcreativity/laravel-json-api#231]
Based on the suggestion (https://laravel-json-api.readthedocs.io/en/latest/basics/validators/#relationships) to write a ticket we are running into the following problem.

We have a resource which has a relationship "creator" a "users" resource like in the example. The issue is 1. the users is deleted so it cannot be found so a 404 status is thrown 2. the creator should be protected, it may not be updated.

Both cases aren't handled in the way the API handles this request. Any suggestions or ways to avoid this behaviour?

**Comment by lindyhopchris** [comment]
Hi!

For (1), the JSON API spec says:

> A server MUST return 404 Not Found when processing a request that references a related resource that does not exist.

Which is why we're sending that `404`. If by deleted you mean *soft-deleted*, i.e. it still exists in the database, then you probably need to see the discussion in this issue: #106 

If clients of your API are still allowed to reference a model that is soft-deleted, then you will need to change your adapter so that it also returns soft-deleted models. I.e. a soft-delete should not remove the model from your API, and a `DELETE` request to your API should do a hard delete, not a soft delete.

I need to add a feature to this package to make this easy to do along with some docs.

For (2), you should add the `creator` relationship to your guarded fields on your adapter. The details are in the into to the relationships section of this chapter: https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/

Let me know if this answers your question or if I've misunderstood your question!

**Comment by svparijs** [comment]
Hi @lindyhopchris thanks for the quick response.

1. Yes I ment _soft-deleted_ resources. The request I'm doing is a PATCH on a resource which has a _soft-deleted_ relationship. So I get the JSON-API definition, but I would like a escape. I will dig into the possibility of adjusting the Adapter to handle this case. But as you mentioned in the #106 ticket this is probably a pretty common case which may be a framework handled thing.

**Comment by lindyhopchris** [comment]
Closing this as handling soft-deleted records is implemented in `1.0.0-beta.6`.
