### ISSUE TITLE
Adapter find Method is called before Middleware

### ISSUE THREAD

**Issue by chris-doehring** [cloudcreativity/laravel-json-api#256]
When defining custom middleware in the `JsonApi::register` options, the find method in any requested `read` action get's called before the middleware kicks in. This is a problem when using a custom authorization middleware and the related resource does require the authorized user scope.

The call which is responsible for this is in the SubstituteBinding: `cloudcreativity/laravel-json-api/src/Http/Middleware/SubstituteBindings.php:81`

I understand that it's needed that way to figure out whether a read route for a resource does exist, but is there a way to execute this AFTER any custom middleware? The current dirty workaround is to always return an empty resource instance when the find method get's called and `Auth::check()` is `false`.

Thanks in advance!

**Comment by lindyhopchris** [comment]
Hi. Sorry for slow reply - crazy work deadline so been a bit busy!

I'm not sure I fully understand your use case, because the default Laravel substitute bindings middleware tends to run before authorization... particularly because the way Laravel's authorization works, you need the record from the database to authorize access to it.

Saying that though I'm open to looking into whether I can use the adapter's exist method at the early point. Then I wouldn't need to substitute the binding as I could use `find` at the first point that I actually require access to the specific record.

Will investigate at some point!

**Comment by rigwit** [comment]
Hi!

I noticed this as well, although not in relation to any custom middleware. I'm still experimenting with the package and haven't added an authentication layer yet. It's really just a base install, but even so, the SubstituteBindings.php causes a model to be retrieved from the database, and then the actual read method on the controller causes a model to be retrieved again.

This is a bit annoying if you fire a 'retrieved' event on the model since the event fires twice. It's of course possible to move the firing of the event to a custom controller, but creating customer controllers just to fire events is a bit overkill compared to the $dispatchesEvents model attribute.

Also, let me just say that you've created a great package. The amount of functionality is quite frankly amazing, and it's all quite easy to understand and work with once you get the hang of it.

**Comment by lindyhopchris** [comment]
@rigwit thanks for the feedback, glad you like the package!

I put the substitute bindings thing in even to make the package more *Laravel-y*, even though the internals of this package don't need it. I'm include to remove it, and can therefore simplify so that the retrieve only happens once. I just need time to investigate that it doesn't have any negative consequences removing it!

**Comment by lindyhopchris** [comment]
Having looked into this, the problem of double-loading is not to do with the binding substitution. It's a problem with the adapter interface. The `read` method on the adapter takes a resource id, whereas every other adapter method that is to do with a specific record takes the record itself.  So the adapter is re-looking up the record even though it has already been substituted.

I think the better solution here is to make the adapter consistent and the read method should take the record being read, not the resource id. The complication is that when filtering on this, we then need to apply the filter to the record itself, and use `exists` on a query builder to check whether the record we've already pulled from the database matches the filter.

**Comment by lindyhopchris** [comment]
@rigwit I've pushed an `issue256` branch that I think fixes this. I'll need to try it out in a couple of the production apps with got before I'm confident it's not massively breaking. Might be good if you could try it too?

**Comment by lindyhopchris** [comment]
@rigwit I've pushed an `issue256` branch that I think fixes this. I'll need to try it out in a couple of the production apps with got before I'm confident it's not massively breaking. Might be good if you could try it too?

**Comment by CyrilSiman** [comment]
Test on my side and it works, thx

**Comment by chris-doehring** [comment]
Hey guys,

first of all: thank you @lindyhopchris for taking the time to take a look at this issue. In the meanwhile, I checked my implementation and found out, that my initial problem with the Auth-Middleware which got executed after the substitute bindings was only a symptom of my real problem. My implementation of the Laravel-Json-API is based on a separate composer package which is being loaded into my Laravel application using the service provider. When doing this, one has to add the class `CloudCreativity\LaravelJsonApi\Http\Middleware\SubstituteBindings` to the same `$middlewarePriority` as the main class `\Illuminate\Routing\Middleware\SubstituteBindings` in the Laravel kernel.

That was pretty hard to find, but now my authorization middleware get's executed before the substitute bindings. Maybe that's a relevant case to add to the documentation, in case others have the same idea?

However, thank you for creating such a nice Json-API package! I will check your change later on as well.
