### ISSUE TITLE
default filter is not always applied when reading entity 

### ISSUE THREAD

**Issue by fibis** [cloudcreativity/laravel-json-api#276]
We have a default fiter, that is checking if the id is in an given array: `$query->whereIn('users.id', $users);`

If the array is emtpy, so the result should always be empty, we getting for the url `/api/users/1?filter[name]=alex` (the name if the user is alex) no data, which is the right behaviour.

If we don't at the filter so the url is `/api/users/1`, we getting as response the user, so the default filter is not applied. Is this the right behaviour?

**Comment by lindyhopchris** [comment]
Hi!

If you're requesting `/api/users/1` then I don't think the package applies any filters if the client has not supplied any filters. The reason being that a request for `GET /api/users/1` without any filters says to give me user number 1 - so that's what the adapter does.

If you supply any filters then `GET /api/users/1?filter[name]=alex` says *give me user number 1 if that user's name is alex*.

You might have to provide me with more information about what you default filter is trying to do. I'm not sure why the default filter will need to filter by user ID when the URL is already scoped to user number 1 anyway.

**Comment by lindyhopchris** [comment]
The original question relates to quite an old version, and I believe the approach described in #337 will cover this use case. If for any reason you think it doesn't, then please comment on #337
