### ISSUE TITLE
Reading record without relationships

### ISSUE THREAD

**Issue by kdevan** [cloudcreativity/laravel-json-api#279]
In a test I've created that creates and then reads the model using doCreate and doRead, I'm finding that when I get to doRead, there's an error due to the record having no relationships.

https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/Concerns/IncludesModels.php#L96-L113

Trace looks something like this:

`./vendor/cloudcreativity/laravel-json-api/src/Eloquent/Concerns/IncludesModels.php:111 { …}
./vendor/cloudcreativity/laravel-json-api/src/Eloquent/AbstractAdapter.php:195 { …}
./vendor/cloudcreativity/laravel-json-api/src/Store/Store.php:105 { …}
./vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php:91 { …}
CloudCreativity\LaravelJsonApi\Http\Controllers\JsonApiController->read() {}`

Starting with a test and ending here.

This method seems to expect that the record has a relationship. If $relationshipPaths is an empty array, this method produces an error. I wonder if I could get some insight here, if this is intentional and I might be doing something else wrong, or if this condition should be fixed to allow for when $relationshipPaths is an empty array in which case I can help and create a PR for that.

**Comment by lindyhopchris** [comment]
I've never seen this, despite having models without relationship paths. What is the error that is thrown? The trace is useful but it would be good to know what the error actually says.

The one comment that I have is that it is not safe to test a create and read in a single request, because it is not realistic for what actually happens. The Laravel app would actually get spun up twice for the two separate HTTP requests, which is not going to happen if you simulate two requests in one test.

Can you refactor your test to split it into one test for the create, and one test for the read, and then let me know if you still get the error?

**Comment by kdevan** [comment]
`#message: "Call to a member function load() on null"`

If there's no loadMissing method and no relationships it would try to run `load` with an empty array and cause the error. It looks like your new commit fixes this! And it looks like there's probably an issue on my end for why the loadMissing method wasn't being found.. I'll troubleshoot there, thank you for the feedback!

**Comment by lindyhopchris** [comment]
Ah ok that makes sense. Glad the new commit fixed it.
