### ISSUE TITLE
Extend ValidatedRequest

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#282]
Hello, is there a way to extend CloudCreativity\LaravelJsonApi\Http\Requests\ValidatedRequest class like with containers? 
For example, i want more then just "getErrors()" in 
"ValidationException($validator->getErrors())"

**Comment by lindyhopchris** [comment]
Each of the controller action methods type-hints a specific request class that extends from the `ValidatedRequest`. So you'd need to extend whichever one you want to override, then bind your extended instance in the container as the class that the controller action is type-hinting.

Out of interest, what more do you want to do than just `getErrors()`? There is a change in the works for the next version that will also attach the validator to the exception rather than just the JSON API error objects.

**Comment by rekrios** [comment]
We are using jsonapi as main api between backend and frontend for our site. I want to send to frontend  via custom Error which one of the standard validators was triggered. For example: 
{
'code' => 'someField-min',
'detail' => 'The someField must be at least NNN'
},
{
'code' => 'name-required',
'detail' => 'The name field is required.'
}
Without ValidatedRequest i can only write something like this in UserValidator(for example)
    protected $messages = [
        'name.required' => 'name-required',
    ];
Now i'm thinking about extending of "AbstractValidators" and making $this->messages in automatic mode in __construct, but its just coz i haven't other solutions

**Comment by lindyhopchris** [comment]
Have you seen this: #263 

Does that do what you're trying to do?

**Comment by rekrios** [comment]
thx, seems the same. I'm waiting for it. rc.1.0.0 ?

**Comment by lindyhopchris** [comment]
Yes I need to make the changes on the `issue263` branch opt-in, then merge it with `develop`, then tag that as `1.0.0-rc.1`. Hopefully in the next week or so!

**Comment by lindyhopchris** [comment]
This has been tagged as `v1.0.0-rc.1`. It's an opt in feature and is documented at the bottom of the Validation chapter.
