### ISSUE TITLE
Question: 'non-resource' requests

### ISSUE THREAD

**Issue by RSpeekenbrink** [cloudcreativity/laravel-json-api#283]
First of all, thanks for the amazing package. This makes working with the JSON:API so much easier. I still have 2 questions though;

1. Is it possible (/good practice) to add extra routes to a resource? For example for an address form I need to get the address based on a POST request of the postcode & housenumber. I think it fits best under '/api/v1/postcodes/address' but can't find anything about this topic in the docs (neither in the JSON:API docs). So whats the best approach here?

2. For now I tried a work around with a custom controller and custom post route. I still want to use the `application/vnd.api+json` Content Type and response. How can I parse the content that got posted (in my case, data->attributes->postcode && data->attributes->house-number) to an array with a custom controller & function? What class/function do I need to use for that from this package?

Thanks a lot!

**Comment by lindyhopchris** [comment]
Hi! Thanks for the feedback, glad you're finding the package useful.

I generally prefer not to add extra routes, because generally I find that I can follow the spec in most cases. Plus also I'm nervous about adding extra routes that might conflict with any additions to the spec in the future.

If you need to get an address based on a postcode and house number, that sounds more like a filter. I.e. you have an *address* resource that can be filtered by post code and house number. I.e. `GET /api/v1/addresses?filter[postcode]=XYZ&filter[housenumber]=123`

Resources can be anything - they don't have to be Eloquent models. If your addresses are stored in a different way, or looked up via a third-party, then all you need to do is write a custom adapter that does the lookup via the different storage or third-party.

However if you do prefer to write a custom route, we've actually now got instructions on how to do this on the `develop` branch. That branch is going to be tagged as `1.0.0-rc.1` in the next week or so. You need to do `composer require cloudcreativity/laravel-json-api:dev-develop` and then follow the custom routes instructions here:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/basics/routing.md

Then the custom action instructions in the controller docs:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/basics/controllers.md

**Comment by RSpeekenbrink** [comment]
What I meant was a route to get data from a third-party to my front end. In this case it was a form to fill in an address and it auto-completes as soon as the housenumber and postcode are filled in. So the address is not actually in the database yet.

The custom routes actually helped with this problem. Thanks!

**Comment by lindyhopchris** [comment]
Ah great, glad to hear that the custom routes helped!
