### ISSUE TITLE
Filters in the scheme

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#287]
Hi. Is there an easy way to access filters from scheme ? Sometimes we are filtering not query, but response information(image sizes). I can parse request or make my own instance of QueryParametersParser, but still I can't see beautiful way of solving this

**Comment by lindyhopchris** [comment]
Hi! You can get the `QueryParametersInterface` instance from the Laravel container - it's bound as a singleton.

You need to be really careful though that this doesn't happen until *after* validation, because an exception will be thrown if the client has sent you query parameters that don't comply with the spec.

Although you can do this, I'd advise not using filters for varying what's in the scheme. That's what [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets) are for. Do those not meet your use-case?

**Comment by rekrios** [comment]
thx, i will try them

**Comment by rekrios** [comment]
Had i understand u correctly ? 
            **app()->make('json-api.request')
                ->getParameters()
                ->getFilteringParameters()**

**Comment by lindyhopchris** [comment]
`app(EncodingParametersInterface::class)`

**Comment by lindyhopchris** [comment]
Ah yes, that's your problem - it was added in beta 6.

**Comment by lindyhopchris** [comment]
Closing this as `1.0.0-beta.6` solved it, and this is all possible in the current version (`1.1.0`).
