### ISSUE TITLE
ValidatedRequest injecting data

### ISSUE THREAD

**Issue by RSpeekenbrink** [cloudcreativity/laravel-json-api#291]
I have a route (users) that controls users in the application. I want to be able to post a new user without a password and then automatically generate a custom password until the user creates it's password via the email notification. First I thought that I can just make a `create()` function in the custom `UsersController` that extends the `JsonApiController` and just check if the password is given on the `ValidatedRequest` and if not just inject it. Then call the parent create with the request and store and it would be good. Although the `$request` is protected in `ValidatedRequest`.

I guess this is probably because of a `ValidatedRequest` is validated and should not be edited anymore. But what is the correct way of doing so? Is it possible to do this logic in the Validator?

Thanks!

**Comment by lindyhopchris** [comment]
Yes the data on the validated request is read-only because it is the data submitted from the client.

This is easily implemented using adapter hooks, which exist for logic related to fill operations (which is what this use case is). The adapter hooks were added in `1.0.0-beta.6` and are documented in the adapters chapter of the docs.

Hope that helps! Close the issue if it does, if not, let me know!

**Comment by RSpeekenbrink** [comment]
Wow, totally missed that in the docs. This is exactly what I was looking for, thanks a lot!

**Comment by lindyhopchris** [comment]
Great! No problem about missing it - that might be because they've only recently been added.
