### ISSUE TITLE
Validators: extend rules() a little

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#300]
Hello. How about extend "protected function rules($record = null)" and add non-mandatory "array $document = []" here, which represent request params ? 
Maybe i'm using not correct way of 'rules', but sometimes i need different rules based on input params. Sometimes some attributes required, sometimes not(for example)

**Comment by lindyhopchris** [comment]
Hi! If you need to conditionally add rules, you should use Laravel's conditional validation:
https://laravel.com/docs/5.7/validation#conditionally-adding-rules

This is already supported, as described under the *Conditionally Adding Rules* section of this chapter:
https://laravel-json-api.readthedocs.io/en/latest/basics/validators/#modify-resource-validation

The reason we don't pass the document to the rules is it is the raw document from the request, i.e. it is not in the format that the validator receives it. Which is why the conditional rules on the validator is a better way to go.

**Comment by rekrios** [comment]
actually i'm doing something like this. It's just that i wanted to prevent overloading update/create methods if my question only about validation rules and anything too complicated

**Comment by lindyhopchris** [comment]
Ah ok, I can see you point. However, I don't really want to change the method signature at this point as I've got it on release candidates at the moment.

I'm not worried about those methods being overloaded as the docs says that's how to do it. I'd also prefer conditional validation to be added in the Laravel way, as I think it's generally better to follow Laravel conventions wherever I can.

Going to close this, but thank you for the suggestion! Do feel free to open any other issues if you have other suggestions!

**Comment by rekrios** [comment]
hi!)
One more suggestion on this topic. Maybe add protected property $document to 'AbstractValidators' class ?
And then make something like this while initializing 
```
    protected function getValidators()
    {
        $validator = $this->container->getValidatorsByResourceType($this->getResourceType());

        if ($validator && $validator instanceof CloudCreativity\LaravelJsonApi\Validation\AbstractValidators) {
            $validator->setDocument($this->decode());
        }

        return $validator;
    }
```
