### ISSUE TITLE
Adapter filter resource on read 

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#309]
Hello,

Consider following filter method in adapter:

```
    /**
     * @inheritDoc
     */
    protected function filter($query, Collection $filters)
    {
        $query->whereNotNull('published_at');
    }
```

In case of `read` action ( for example `/posts/1` ) and `post` is actually not published ( `published_at` is `NULL` ) returns following response:

```
{
    "data": null
}
```

I was wondering, shouldn't it be 404 instead of `null` response above?
If it is correct approach `read` method should be updated to something like that I guess:

```
    /**
     * @inheritDoc
     */
    public function read($record, EncodingParametersInterface $parameters)
    {
        $parameters = $this->getQueryParameters($parameters);

        if (!empty($parameters->getFilteringParameters())) {
            $record = $this->readWithFilters($record, $parameters);
        }
        
        if (!$record) {
            throw new ResourceNotFoundException("@TODO: get resource", "@TODO: get resource id");
        }

        $this->load($record, $parameters);

        return $record;
    }
```

Thanks

**Comment by lindyhopchris** [comment]
Hi! Thanks for the question. According to the spec:

> A server MUST respond to a successful request to fetch an individual resource with a resource object or `null` provided as the response document’s primary data.
> `null` is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn’t currently.

https://jsonapi.org/format/#fetching-resources

I think the `null` response is therefore appropriate if an individual resource does not match filters, because it could in correspond to a single resource if the filtered value changes. E.g. if the resource becomes published in your example.

However, if it is the case that your API only returns published posts, then you are correct that a `404` response would be more appropriate. The `filter` method is actually only called if the client provides values in the `filter` query parameter. Therefore you would actually need to overload the `newQuery()` method if you wanted unpublished resources to never appear in the API:

```php
protected function newQuery()
{
   return parent::newQuery()->whereNotNull('published_at');
}
```

Alternatively if posts should appear in your API regardless of whether they are published, the filter method should actually be:

```php
protected function filter($query, Collection $filters)
{
  if ($filters->has('published')) {
    $query->whereNotNulll('published_at');
  }
}
```

Otherwise the client can never toggle whether it is asking for published or not published resources.

**Comment by lindyhopchris** [comment]
Should have said, if you made the above change to the `newQuery()` method you'll get a `404` if requesting an id that is an unpublished resource.

**Comment by deividaspetraitis** [comment]
Thank you for detailed answer!
