### ISSUE TITLE
Routing for polymorphic relationships

### ISSUE THREAD

**Issue by Wizofgoz** [cloudcreativity/laravel-json-api#314]
Are registering of routes for polymorphic relationships supported? In the docs for routing, this is what is said:

> The related resource type needs to be known so that the query parameters for requests to relationship routes can be validated correctly. For example, for a _to-many_ relationship, the filters that are allowed will be those allowed for the related resource type. So a request to `posts/1/author` will need to validate the filters for those allowed for `users` resources, not the posts resource.

**Comment by lindyhopchris** [comment]
This isn't fully tested at the moment. The way I've got things set up it in theory works but there's likely to be some bugs in it - particularly how to go about validating query params for polymorph relations. This is because query params on relation routes are validated by the inverse resource type (i.e. the resource that is in the relationship), but for polymorphs there are many inverse resource types.

So support is a bit patchy at the moment. I need to add tests for this scenario so that I can check it actually works and iron out any potential bugs (which I suspect there might be a few).

**Comment by osteel** [comment]
Hey there – I was wondering if there was any progress on this? It doesn't look like JSON:API really supports this, so did you mean you were working on something that would act as a bridge between Eloquent's polymorphic relationships and the JSON:API specification @lindyhopchris?

**Comment by lindyhopchris** [comment]
@osteel can you let me know what you're trying to do with polymorphic relations, then I can advise whether it's supported in this version or not?

I'm working on the new version at the moment, which will include full support for polymorphic resources.

**Comment by osteel** [comment]
@lindyhopchris I was just being curious really, as I'm currently working with polymorphic relationships and realised JSON:API doesn't really support them. For the time being, it looks like the fact that the `HasOne` and `HasMany` rules accept multiple resource types does the trick for me (although I still need it to test it), but yeah I'm curious to see how you're intending to support this further!

Feel free to ignore this though 😉

**Comment by lindyhopchris** [comment]
Ah great, thanks for confirming!

**Comment by lindyhopchris** [comment]
Now tracking polymorphic issues in the new package on this issue:
https://github.com/laravel-json-api/laravel/issues/8
