### ISSUE TITLE
Included resources pagination

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#319]
Hello,

Before explaining further I would like to notice though there was a similar issue but still I'm not sure is it solved or not: https://github.com/cloudcreativity/laravel-json-api/issues/46 and this case is a bit different.

The idea is be able to paginate/limit included resources, consider following request: `users/1?include=followers&page[followers][size]=10&page[followers][number]=1 `

I think it totally makes sense to limit included resourses ( in some cases to paginate as well?  ) instead of making separate request to `/users/1/followers?page[size]=10`.

Please correct if I'm wrong but after some research I found this solution would be valid according  JsonAPI spec. too ( i.e. https://discuss.jsonapi.org/t/how-to-handle-an-excessive-number-of-included-resources/209/3 ).

The question is now is there any easy way to implement such functionality using this package?

**Comment by lindyhopchris** [comment]
#46 is to do with pagination on related resource routes, e.g. paginating a post's comments on the URL `/api/v1/posts/1/comments`. That is now fully supported, but is different from being able to page included resources.

So you can implement this yourself in your schema. I haven't tried this myself but it would be something like this:

```php

    /**
     * @param Post $resource
     * @param bool $isPrimary
     * @param array $includeRelationships
     * @return array
     */
    public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'comments' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::SHOW_DATA => isset($includeRelationships['comments']),
                self::DATA => function () use ($resource) {
                    return $resource->processes()->orderBy('created_at', 'desc')->take(10)->get();
                },
                self::LINKS => [
                    'next' => $this->createLink(
                        "/posts/{$resource->getRouteKey()}/relationships/comments?" . http_build_query([
                            'page' => ['number' => '2', 'size' => '10'],
                        ])
                    ),
                ],
            ],
        ];
    }
```

The **big** problem with this is you remove all eager loading and get the classic *n+1* problem. As per this comment, the solution is to work out a better request for your client to send:
https://github.com/laravel/framework/issues/18014#issuecomment-412796586

**Comment by lindyhopchris** [comment]
For info, our approach is never to include the `data` member for a has-many relationship that can potentially include very lengthy lists, as we choose to not expose something to the client that would be exceptionally inefficient to request - i.e. because it would result in tonnes of included resources.

There's no way in the spec to specify paging of included resources - that `page` parameter refers to paging the primary resource of the response (i.e. whatever is in the `data` member of the document).

**Comment by deividaspetraitis** [comment]
Very informative reply, appreciate! Just to note, I thought about the idea to have pagination just to be able _to limit included resources_ as I have mentioned previously.

For example I need display a resource with its 3 related resources in a single page: `followers`, `tickets` and `comments`. 

Please correct me if I'm wrong but it should be more efficient to do that in the single request `/users/1?include=followers,tickets,comments` rather than sending 3 separate requests for included: `/followers?filter[user_id]=1&filter[limit]=10`, `/tickets?filter[user_id]=1&filter[limit]=10`,  `/comments?filter[user_id]=1&filter[limit]=10`

In case `1` request instead `n` approach is more appropriate only the issue is to be able to limit included resources, since pagination will not work out here, I think it will be valid and correct to apply some filters, i.e.  `/users/1?include=followers,tickets,comments&filter[followers][limit]=10&filter[tickets][limit]=10&filter[comments][limit]=10`


Please let me know I'm on the right track or not, thanks. :) 

Since the question regarding pagintion is already answered and this conversation is likely becoming more about spec it self not about package I'm closing this issue.

**Comment by lindyhopchris** [comment]
Yeah this is really difficult, I'm not sure what the correct approach is myself. You'd have the same problem if you were rendering the DOM using Laravel's Blade templates... i.e. how to avoid the n+1 problem when you only want to eager load the first few of each eager loaded relationship.

That's exactly what this issue is about:
https://github.com/laravel/framework/issues/18014

In terms of what's the most efficient way of requesting it, my tip would be to work out what the most efficient way of doing it with your DB setup - i.e. work out the best way of loading the models for what you want to do if you were just iterating over the models in your PHP code. Then effectively ensure that your API allows the client to request the data in the same efficient way.

Let me know how you get on!
