### ISSUE TITLE
How to use translated slugs as IDs?

### ISSUE THREAD

**Issue by arad0s** [cloudcreativity/laravel-json-api#323]
I'm developing an app with translatable models, which means some resources have attributes in 
more than one language .

In the database, each translatable model has a translations table, which has:
- A foreign key to the model table
- A 'locale' column
- Columns for each translated attribute

For example, the 'posts' resource has a 'slug' attribute, which has different values on different languages, and therefore the 'slug' column resides in the the 'post_translations' table.

Now, I want to use the translated 'slug' attribute as the ID for the 'posts' resource.
I modified the schema's getId method, and the adapter's $primaryKey property, as per the documentation.

Since the $primaryKey property I set on the adapter is not a field of the 'post' eloquent model, I have to perform a join operation (between the 'posts' and 'post_translations' tables) before any query that involves the adapter's $primaryKey property is performed.

My solution was performing the join operation by adding a global scope to the 'post' model, which I consider inefficient, since the join will be performed with each query related to the 'post' model.

What is the best practice for using the slug as ID in this kind of scenario?

**Comment by lindyhopchris** [comment]
Interesting question!

So my advice would be against translating resource ids. The resource id is like a *constant*, it shouldn't really change. Remember that what you use as the resource id, you have to use this consistently throughout your API - so if the post resource is in a relationship, the id in that relationship must also match the id on the resource.

How I'd approach this depends on the use case. If you have no expectation that API clients would access multiple locales at once, I'd scope the API by locale. I.e.:

`GET http://example.com/api/en/posts/1` would get post 1, which would be translated as English.

`GET http://example.com/api/en/posts?filter[slug]=my-first-post` would get a post that had an English slug of `my-first-post`.

It would then be up to the client as to which locale API it is connecting to.

If you really must have a resource id that is specific to the locale, then rather than using the slug I'd suggest using the primary key and the locale, rather than the translated slug. E.g. `123-en` or `en-123` would mean the post 123 translated with locale `en`. The advantage with this is that wherever you receive it you do not need to do the database join - you just extract the `123` bit of the id and use it directly.

Remember that the classic use of slugs is to give a human friendly URL. For example, you want a human to see `http://example.com/blog/my-first-post` in their browser. This doesn't really apply to an API though - because the end-user doesn't see the API requests.

So if for example visiting that blog URL in your browser triggers an API request, behind the scenes the browser can send either of these two request, which of course the user doesn't see:

- `http://example.com/api/en/posts?filter[slug]=my-first-post` which return a post with id `123`; or
- `http://example.com/api/posts?filter[slug]=my-first-post` which returns a post with id `123-en`.
