### ISSUE TITLE
Support adapter scopes via global scopes

### ISSUE THREAD

**Issue by andreas83** [cloudcreativity/laravel-json-api#337]
whats the best way to protect a resource, i.e. user should be able to only read/update/delete own resources....

**Comment by lindyhopchris** [comment]
Ah yes, so we use a piece of middleware to apply a [global scope](https://laravel.com/docs/5.8/eloquent#global-scopes) to our model class.

I've had a rough idea to allow you to pass something that implements the `Scope` interface to the adapter constructor to make this a bit more intuitive to use. If you think a scope would do it, then let me know and I can probably get this added in very easily.

**Comment by andreas83** [comment]
A thanks for pointing me into the right direction and sorry for bothering you. 
I will go with the global scope for now.

**Comment by lindyhopchris** [comment]
I'm going to re-open this as I feel this is potentially a common use case. I therefore either need to:

- Document adding global scopes via middleware as the recommended approach; and/or
- Support scopes being added to adapters.

So re-opening this so I don't forget about it!

**Comment by lindyhopchris** [comment]
@andreas83 I've added support for adapter scopes on the `issue337` branch. Could you take a look at check whether it would meet your requirements? If you want to give it a go, you can install as follows:

```bash
$ composer require cloudcreativity/laravel-json-api:dev-issue337
```

This branch adds an `addScopes` and `addClouseScope` methods to the Eloquent adapter. The first allows you to add scope objects that implement Laravel's `Scope` interface. E.g. could use it via constructor dependency injection in your adapter:

```php
public function __construct(\App\Scopes\UserScope $scope)
{
  parent::__construct(new \App\Post());
  $this->addScopes($scope);
}
```

Or you could use either method via a container event binding, for example to add a closure scope in your `AppServiceProvider::register()` method:

```php
$this->app->afterResolving(App\JsonApi\Posts\Adapter::class, function ($adapter) {
  $adapter->addClosureScope(function ($query) {
    $query->where('author_id', \Auth::id());
  });
});
```

Personally we prefer constructor injection, but either works fine!

**Comment by freddy38510** [comment]
Why not doing that restriction in a global Authorizer ?

Like this:
`public function update($record, $request)
{
    if($record->user_id !== \Auth::user()->id) {
        throw new AuthorizationException;
    }
}
`

**Comment by lindyhopchris** [comment]
You can do it that way if you want - it depends on the design of your API.

If your API only ever serves resources that relate to the current user, then your approach might be to make all other user's resources *never* appear... i.e. from the client's perspective, they don't exist. In this case, the global scope and `404` response is a very good approach.

If your API serves a mixture of resources belonging to different users, but the user can only access some... then the Authorization exception is the better way to go. I.e. the client can tell the resource exists (because it doesn't get a `404` response), but just can't access it - i.e. gets a `403` or `401` response depending on whether the user has authenticated.

**Comment by freddy38510** [comment]
Oh ok i see the distinction you made between these two approaches. I didn't think of this case. Maybe you could elaborate more about this little nuance in the docs for global scopes. I mean, in the current example : 

> An example use would be if you only want a user to access their own `posts`
resources - you would add a scope to the `posts` adapter.

Otherwise it could cause confusion like it happened to me.

An other valid option would be to use the filter method in the resource Adapter. It's a little tricky, but i think it's working for a request without filters.

```php
protected function filter($query, Collection $filters)
{
    $query->where('author_id', \Auth::id());
}

**Comment by lindyhopchris** [comment]
@freddy38510 thanks for the feedback, I've added something to the docs about this.
