### ISSUE TITLE
Refactor cursor-based pagination strategy to be inline with profile

### ISSUE THREAD

**Issue by jelhan** [cloudcreativity/laravel-json-api#338]
In October last year a cursor-based pagination strategy was published as example profile. You could find it here: https://jsonapi.org/profiles/ethanresnick/cursor-pagination/ It would be great if we could refactor cursor-based pagination strategy delivered with these package to be complaint with that profile.

**Comment by lindyhopchris** [comment]
Totally agree. Though we should not refactor the existing one, we should provide it as an additional strategy. This is because we have documented APIs that are using the existing cursor strategy, so it would be breaking for clients if we refactored the strategy.

I would however be happy deprecating the existing cursor strategy and changing the documentation so that it matches the new one and says that it complies with that profile.

If you want this quickly, you'd need to submit a PR that adds in the new cursor strategy. I'm afraid it won't be a priority for us to update the cursor strategy because we don't have a need to use that profile at this time.

**Comment by jelhan** [comment]
We might want to rename the existing `CursorStrategy` in `v2` to free that name for the profile.

**Comment by lindyhopchris** [comment]
Yeah could definitely do that.

The alternative would be to have a `CloudCreativity\LaravelJsonApi\Profiles\{ProfileName}` namespace... then there wouldn't be a collision with the old name anyway.

Or alternatively, put each profile in its own package, so you use Composer to pull in the profiles you want your API to support.

Need to decide on one of those approaches when JSON API actually tags its profile implementation. From some of the recent chatter about it, I'm unsure which version it might actually be tagged in (but haven't looked at the discussions in about 4 weeks).

**Comment by lindyhopchris** [comment]
Closing this issue as it's really old, and JSON:API have never actually released profiles.

We can revisit in the new package if JSON:API does publish 1.1 with profiles. My preference for profiles would be for them to always work as packages that you require if you're using them... e.g. for this have a `laravel-json-api/profile-cursor-pagination` package.

However, I'd only spend the time doing the work on profiles if they're actually released by JSON:API - as there's plenty of other things to be getting on in the meantime!
