### ISSUE TITLE
Fields not available in schema after creation

### ISSUE THREAD

**Issue by jaysson** [cloudcreativity/laravel-json-api#344]
When I create a resource, only the fields I submitted are received back. I am using postgres.

```
POST /api/v1/orders
{
    "data": {
        "type": "orders",
        "attributes": {
            "deliverOn": null,
            "customerId": "1"
        }
    }
}
```
However, there are more fields in the table with default values. These values are mentioned in schema array.

```php
// Schema.php
public function getAttributes($resource)
{
    return [
       // Other fields
       'itemsTotal' => $resource->items_total->toFloat(),
    ];
}
```
`itemsTotal` should be 0. It throws error saying toFloat cannot be called on items_total. items_total has an attribute accessor that returns `Decimal`.

Currently I am adding `$resource->refresh()` in schema. But this should not be necessary.

**Comment by lindyhopchris** [comment]
Hi,

So I can't comment on the `toFloat` error because that's not something to do with this package and is down to your application.

The `$resource->refresh()` is unnecessary as you say, and would be highly inefficient in an API so definitely remove that.

Check that you've correctly added the right resource to model mapping in your JSON API config.

Otherwise I'm sorry to say there's not much for me to go on based on the above information you've shared. I've never seen anything like attributes going missing - my best guess would be that the schema you think is being used is not actually the one that is being used. Is the `Schema.php` that you've shared the excerpt from definitely the `App\JsonApi\Orders\Schema` class? (Or whatever namespacing you are using in your app?)

**Comment by jaysson** [comment]
You can ignore toFloat part. The issue is that fields are missing from the model. The config is alright, it is from the correct schema file. I will link to a repo reproducing the issue today.

**Comment by lindyhopchris** [comment]
Yes you'll need to do that because we've never seen this issue and the package is in use in multiple production systems.

**Comment by k8n** [comment]
I'm experiencing something similar. An attribute that is set/updated in my model's save() method is not returned.

**Comment by lindyhopchris** [comment]
Is it definitely mass-assignable on your model?

**Comment by jaysson** [comment]
Took a few days for me to come back to this, but here is a repository that demonstrates the issue.

https://github.com/jaysson/jsonapi-laravel-344

**Comment by jaysson** [comment]
For now, I am doing this in my adapter.
```php
  /**
   * @param Eloquent $record
   * @return AsynchronousProcess|void|null
   */
  protected function persist($record)
  {
    parent::persist($record); // TODO: Change the autogenerated stub
    $record->refresh();
  }
```

**Comment by lindyhopchris** [comment]
@jaysson what HTTP request are you sending, and what does the response look like? I'm still sceptical about this one, because all our production apps would be failing if this package was broken in this way, so still suspect it's something else.

**Comment by jaysson** [comment]
I have described the HTTP requests in the readme - https://github.com/jaysson/jsonapi-laravel-344

Pasting it here:

## Create post
### Request
`POST /api/v1/posts`
```json
{
	"data": {
		"type": "posts",
		"attributes": {
			"description": "The description"
		}
	}
}
```
### Response
```json
{
    "data": {
        "type": "posts",
        "id": "4",
        "attributes": {
            "description": "The description",
            "updated_at": "2019-05-08 08:50:24",
            "created_at": "2019-05-08 08:50:24"
        },
        "links": {
            "self": "http://localhost:8000/api/v1/posts/4"
        }
    }
}
```
## Fetch
`GET /api/v1/posts/1`

```json
{
  "data": {
    "type": "posts",
    "id": "4",
    "attributes": {
      "title": "A default title",
      "description": "The description",
      "created_at": "2019-05-08 08:50:24",
      "updated_at": "2019-05-08 08:50:24"
    },
    "links": {
      "self": "http://localhost:8000/api/v1/posts/4"
    }
  }
}
```
Seems to be an issue in eloquent itself. There is a closed issue - https://github.com/laravel/framework/issues/21449

**Comment by lindyhopchris** [comment]
Ah great, sorry that I missed that in the readme.

This is really useful as it means I now understand what the issue is that you're encountering. This is definitely an Eloquent issue not an issue with this package. Eloquent doesn't load in any default values assigned in the database.

There's two ways of approaching this:

1. Define a `$attributes` on your model class with the default values. We do this in some cases, the downside is you have to keep those default model attributes in sync with the default values your database assigns.

2. Reload the model after first saving it to the database. That's the workaround that you've put in.

For your workaround, you can use [adapter hooks](https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#adapter-hooks) to better implement this:

```php
class Adapter extends AbstractAdapter
{
    // ...

    protected function created(Post $post): void
    {
        $post->refresh();
    }
}
```

Can you give that a go and then close the issue if you're happy that it solves your problem?

**Comment by jaysson** [comment]
That works, thanks.
