### ISSUE TITLE
Controller names should be singular, as per Laravel naming conventions

### ISSUE THREAD

**Issue by charliegilmanuk** [cloudcreativity/laravel-json-api#352]
I'm transitioning my application to this package, up till now I had been using Laravel's naming conventions for my controllers, so `PostController` not `PostsController`.

[Laravel naming conventions](https://webdevetc.com/blog/laravel-naming-conventions#section_method-naming-conventions-in-controllers)

I was a bit confused as to why this is not the case by default with this package, just means that in order to extend my controllers the names have to be explicitly defined, I see no reason to deviate from the conventions.

```php
$api->resource('quotes')->controller('QuoteController')
```

Is there a way for me to configure this if it can't be made default for the package?

**Comment by lindyhopchris** [comment]
Ah it's because we're following the JSON API convention of pluralising the resource name.

I'd be open to making this a setting in the API's config file though, so that you can toggle it to the singular (the default setting would need to be to pluralise it, as that's the default at the moment). 

Any chance you could do a PR?

**Comment by lindyhopchris** [comment]
Added a `singularControllers()` helper method. Will be in the next release: `v1.3.0`.

Usage is as follows:

```php
JsonApi::register('default')
    ->withNamespace('Api')
    ->singularControllers()
    ->routes(function ($api, $router) {
        $api->resource('posts')->controller(); // uses PostController
    });
```
