### ISSUE TITLE
Support Channels?

### ISSUE THREAD

**Issue by kervinpierre** [cloudcreativity/laravel-json-api#354]
Is there a community group available for discussing this project?

Do any of the authors consult around the package?

I looked around the docs and the GitHub but didn't find anything.

**Comment by lindyhopchris** [comment]
Hi! Thanks for raising this. To-date I've used Github issues to discuss any questions or ideas related to this project. I would however be totally open to setting up a discussion group if people would find that useful.

The only thing that I'd say though is I can't sit around all day answering people's support questions, because that would have an impact on my paid work! A discussion group is likely to result in such support questions. But if there's a number of people that would be willing to help field questions so it's not 100% down to me, then that would be great.

Did you have something in mind for a group to use? My preference would be Discord.

**Comment by kervinpierre** [comment]
I was thinking of Discord as well.  I think once t here's a general sense of FAQ others may join in.  And Discord's history/search have been an incredible help to me in the past.  

Are you available for paid consulting?  I'm also looking for high-level design advice and possibly the occasional design or code review.

**Comment by lindyhopchris** [comment]
OK I'll get a Discord channel set up when I next have time.

Thanks for asking, but I'm not available for paid consulting at the moment as I'm fully occupied and will be until the end of the year.

**Comment by kervinpierre** [comment]
If you'd like, I can create the discord server/group then pass ownership to you, just to get things started.

Does that work?

**Comment by lindyhopchris** [comment]
@kervinpierre I've created a `laravel-json-api` server. Can you see it and get into it? I could probably do with some help setting it up, as I've only *consumed* stuff on Discord before, never set anything up!

**Comment by kervinpierre** [comment]
Hi,
I was never able to find the server.  Nothing comes up
![image](https://user-images.githubusercontent.com/350213/60692338-89c8b200-9ea3-11e9-86a3-d70895830d52.png)

**Comment by lindyhopchris** [comment]
@kervinpierre I can't seem to find a setting anywhere that allows me to make it discoverable. This is the first time I've created a server on Discord though so I'm a bit clueless!

Here's an invite link that works for a day...
https://discord.gg/XuN9wA

If you join I can make you an admin and then you can help me figure it out!!!

**Comment by kervinpierre** [comment]
I'd love to, but I just saw this.  Could you please email the invite code to kervinpierre@gmail.com?

Takes me a few days to get to my Github notifications.

**Comment by cunhar** [comment]
did this server ever get setup?

**Comment by lindyhopchris** [comment]
sort of, but I'm in two minds as to whether to use Discord or Slack. I'm also extremely busy with work for the upcoming SCA changes to web payments, so won't really make a decision until late September.

Out of interest, does anyone have strong preferences as to where a community board is hosted?

**Comment by cunhar** [comment]
thanks for the awesomely fast reply as always @lindyhopchris 

I personally like discord because of the whole being free thing :D 

I'm extremely interested in contributing to your project as I am leading a new api project using your library.  I could begin be helping set this up and getting more people involved.

**Comment by lindyhopchris** [comment]
Just revisited this. I've used Slack instead as it's easier for me as I also use Slack for work - so can have everything in one place.

[Here is an invite link.](https://join.slack.com/t/laraveljsonapi/shared_invite/zt-cytptxic-ug_UVVMExSAWT5m1sc21nw)
