### ISSUE TITLE
How to utilize resource type to multiple PHP classes mapping?

### ISSUE THREAD

**Issue by arad0s** [cloudcreativity/laravel-json-api#355]
It states in the documentation that:

> You can also map a resource type to multiple PHP classes as follows:
```
'resources' => [
    // ...
    'tags' => [\App\UserTag::class, \App\SystemTag::class],
]
```

I also read this issue #130, and I was wondering how to utilize this feature:

- What should I do except for mapping the resource type in the config to multiple PHP classes?
- How should I structure the adapter and schema for the _tags_ resource in this case?
- What are the API implications of mapping a resource type to multiple PHP classes?

**Comment by lindyhopchris** [comment]
Hi!

> What should I do except for mapping the resource type in the config to multiple PHP classes?

You don't need to do anything else. What this mapping means is if the encoder encounters either of those two PHP classes, it will use the `tags` schema to convert them to JSON API resources.

> How should I structure the adapter and schema for the tags resource in this case?

Your adapter, schema and validators classes will all be for the `tags` resource... i.e. you have one set, and they will be expected to handle API resources that relate to any of the model classes.

> What are the API implications of mapping a resource type to multiple PHP classes?

The main thing is how you do you resource `id`, as the resource `type` will always be `tags`. So let's say both `UserTag` and `SystemTag` use numeric model keys, you won't be able to use that for your resource id. Because if a client requests `tags` with an id of `123`, is that a `UserTag` or a `SystemTag`? In this example you'd probably want to put something in the id that differentiates which model it relates to, and then you'll need to program your adapter to handle these. In contrast, if your models use UUIDs then you wouldn't need to do this... you'd just need to program the adapter to check one table then the other.

The other implication is doing pagination... it's a lot harder to support pagination when you have models sitting in two different tables. Page based pagination won't work, you'd need to come up with some sort of custom pagination that is capable of checking two lots of tables.

Let me know if you've got any other specific questions about this!
