### ISSUE TITLE
Create resource and associate belongsTo resource

### ISSUE THREAD

**Issue by seguer** [cloudcreativity/laravel-json-api#359]
Hi, I've got what I think should be a fairly simple set up with User and Company (User belongsTo Company).

When creating a User resource however, the Company is not assigned to the user (company_id column is left null). Interestingly, I am able to attach multiple Roles to the User perfectly fine.

The create request looks like the following:

```
{
	"data": {
		"type": "users",
		"attributes": {
			"email": "testing@example.com",
			"password": "testingpassword",
			"password_confirmation": "testingpassword",
			"name": "Testing Account"
		},
		"relationships": {
			"company": {
				"data": {
					"type": "companies",
					"id": "1"
				}
			},
			"roles": {
				"data": [
					{
						"type": "roles",
						"id": "1"
					}
				]
			}
		}
	}
}
```

The Roles are attached fine, but Company does not populate company_id. Note that the user is correctly created, with the attached roles. Just not the Company.

Relevant part of User Adapter:

```
protected function company()
{
    return $this->belongsTo();
}
```

Relevant part of User Schema:

```
public function getRelationships($resource, $isPrimary, array $includeRelationships)
{
    return [
        'company' => [
            self::SHOW_SELF => true,
            self::SHOW_RELATED => true,
            self::SHOW_DATA => isset($includedRelationships['company']),
            self::DATA => function () use ($resource) {
                return $resource->company;
            },
        ],
        'roles' => [
            self::DATA => function () use ($resource) {
                return $resource->roles;
            },
        ],
    ];
}
```

Relevant part of User Model:

```
public function company()
{
    return $this->belongsTo(Company::class);
}
```

For Users that have a company_id, requesting a User (read/show) brings back the Company data fine.

Have I missed something?

**Comment by lindyhopchris** [comment]
Hi! Really sorry for slow reply on this - didn't spot the notification that you'd created the issue.

Can you share the code for the whole of your user adapter? It's likely to be something in that. Populating belongs-to relationships on create is tested and working, so I suspect something on your adapter is the problem.

**Comment by seguer** [comment]
Hi, no worries - please see the gist for the entire User Adapter file.

https://gist.github.com/seguer/6869814058231a88193a2058ebbfcd73

**Comment by lindyhopchris** [comment]
Hmmm, ok I'm a bit perplexed!! I can't see anything obviously wrong there. 

If this wasn't working as you describe, they'd be a lot of failing tests - both in this package plus the production apps we have using it...

This requires a bit of debugging that it's not really possible for me to do via this issue....

Are you able to debug what happens when the adapter is invoked for the create request? It lands in the adapter in the `create` method, which can be found here:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Adapter/AbstractResourceAdapter.php#L89

**Comment by lindyhopchris** [comment]
Also I'm assuming you're on at least `v1.0.0` - if not let me know.

**Comment by seguer** [comment]
Hi, yes, version defined as ^1.1. Sorry the delay, we had a long weekend over here :).

That method receives the following:

```
array:1 [
  "data" => array:3 [
    "type" => "users"
    "attributes" => array:4 [
      "email" => "testing@example.com"
      "password" => "testingpassword"
      "password_confirmation" => "testingpassword"
      "name" => "Testing Account"
    ]
    "relationships" => array:2 [
      "company" => array:1 [
        "data" => array:2 [
          "type" => "companies"
          "id" => "1"
        ]
      ]
      "roles" => array:1 [
        "data" => array:1 [
          0 => array:2 [
            "type" => "roles"
            "id" => "1"
          ]
        ]
      ]
    ]
  ]
]

EncodingParameters {#269
  -includePaths: null
  -fieldSets: null
  -sortParameters: null
  -pagingParameters: null
  -filteringParameters: null
  -unrecognizedParams: null
}
```

When it creates the record, it creates what appears to be an empty User object (it serialises to ``[]`` as JSON).

It then moves into L306 (``fillAndPersist``) where it runs all the way through to return the ``$record`` (User object, without company_id set). On L324 there's an empty method with the comment ``// no-op`` (``fillRelated``)

**Comment by lindyhopchris** [comment]
No problem about the delay! Totally get that we don't all work all the time (thankfully!)

The `fillRelated` is no-op in that abstract resource adapter, but is implemented in the Eloquent adapter. It's definitely working because that's what does the creation of the roles relationship.

So that all looks good above, can't see any problems. What happens is during the `fillAndPersist` it should hand the filling of the company relationship off to the belongs-to relationship class. That results in these lines being called:

https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/BelongsTo.php#L82-L91

In that method, it will look up the relationship of `companies:1`. Does company model with id 1 get found at that point? If not, it will end up setting the relationship to `null`. If you have any global scopes etc in play, that means it cannot find company 1 at that point, that will obviously have an affect.

If you could see what it does when it hits that method that would be great. If it's not hitting that method, then for some reason your adapter is deciding not to fill the relationship. That would need to be debugged in these lines:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Adapter/AbstractResourceAdapter.php#L253-L263

Sorry for having to ask you to debug so much... this is probably something I could work out in a couple of minutes if it was code I had hands-on access to but is pretty difficult doing it via Github issues.

**Comment by seguer** [comment]
Alright debugging and tracing through, we get to L86 in ``BelongsTo`` so it is trying to associate something.

``$relation`` is a BelongsTo which has User details (from the create data).

``$related`` is a.. User model. That doesn't seem right.

``$relationship`` is accurately companies and id 1 (in my create POST).

Digging further, looking at ``Store/Store.php``'s ``find()`` method:

The ``$identifier`` gets the correct type (companies) and id (1), but ``$record`` initially returns null. When it then tries to run adapterFor and find, it returns a ``User`` object. This is likely where the problem lies!

**Comment by lindyhopchris** [comment]
So the problem is in your `companies` adapter. What model are you injecting in the constructor of that adapter?

**Comment by seguer** [comment]
Hah! Oh man. That was it. I was using User there. I knew it was something dumb, somewhere, and I must have kept looking over the constructor.

Thanks for your patience and help! It now works as expected.

**Comment by lindyhopchris** [comment]
Ah don't worry about it - has happened to us all at some point! Glad it's now working.
