### ISSUE TITLE
Has-Many-Through relationship read only status

### ISSUE THREAD

**Issue by X-Coder264** [cloudcreativity/laravel-json-api#372]
We are using the [Trim](https://trikoder.github.io/trim/) "framework" to build really powerful admin user interfaces that connect to a JSON API powered backend by this package.

The problem we are currently facing is that the has-many-through relationship in this package is read only as stated in the documentation:

> The JSON API hasManyThrough relation can be used for an Eloquent hasManyThrough relation. The important thing to note about this relationship is it is read-only. This is because the relationship can be modified in your API by modifying the intermediary model.

Modifying the intermediary model in our case isn't a viable solution for us as that requires (in the context of Trim) to create a whole new admin interface just for that.

For example let's take an example from the Trim demo:

https://trikoder.github.io/trim/demo/index.html#/page/1

This is the edit interface of the `page` entity which has a has many through relationship with the `tag` entity. Without having write support for the hasManyThrough relation in this package changing the tags in this admin doesn't work/doesn't have any effect.

Having to create a new admin interface just for the intermediary model means that the UX/UI experience is much worse as that means that the user can edit everything about the `page` entity in its edit form, but in order to edit the page's tags the user has to go in an entirely separate admin and make the changes there.

So my question is basically if there is any technical reason why the package couldn't support writing the hasManyThrough relation?

**Comment by lindyhopchris** [comment]
Hi! So I don't understand what the intermediary model is in the page > tag relationship? Wouldn't page and tag be a belongs-to-many in Eloquent terms? That is writable via this package.

The reason we haven't implemented writing for has-many-through, is because it is highly likely that the intermediary model requires attributes to be created (because otherwise a belongs-to-many would be in use). As the relationship identifiers do not include attributes, the way to create the intermediary resource would be to `POST` the intermediary resource.

If your scenario is definitely a has-many-through, and the intermediary model does not need any attributes in addition to the two foreign-keys to be created, then I can see the use-case for this functionality.

**Comment by X-Coder264** [comment]
Sorry for bothering you. The relationship in our case was actually badly modeled as a has many through even though a belongs to many would suffice which lead to me unnecessarily opening this issue. I'm closing this issue as using a belongs to many relationship fixes all our problems. Thanks for the support.

**Comment by lindyhopchris** [comment]
No problem! Glad you got it working and thanks for closing the issue.
