### ISSUE TITLE
Creating hasMany relationships with repeated data

### ISSUE THREAD

**Issue by vlavlad** [cloudcreativity/laravel-json-api#376]
Hi @lindyhopchris, I spotted the new issue that may help to make the library better.
When I'm trying to create the resource that has hasMany relationship, the repeated values saving as one. I need to have repeated values for hasMany relationship.

Could you help me to find out the way how can I achieve it? Is this case reasonable for JSON API?

URI
`/api/v1/experiments`

Here the POST data that I'm trying to pass.
```
{  
   "data":{  
      "type":"experiments",
      "attributes":{  
         "name":"Test 2",
         "description":""
      },
      "relationships":{  
         "storages":{  
            "data":[  
               {  
                  "id":"102",
                  "type":"storages"
               },
               {  
                  "id":"102",
                  "type":"storages"
               }
            ]
         }
      }
   }
}
```

**Comment by lindyhopchris** [comment]
Hi!

This is against the JSON API spec, which says for has-many relationships:

> If a given type and id is already in the relationship, the server MUST NOT add it again.
> https://jsonapi.org/format/#crud-updating-to-many-relationships

I.e. our implementation is correct in that it only allows a resource identifier to appear once in a relationship. Note also that the spec is clear that the order in which identifiers appear in a relationship is not significant.

What you are trying to do though is implementable however. You'd need to model the relationship as an intermediary resource, with its own resource id that represents that specific linkage between the `experiments` resource and the `storages` resource. Your create logic for the intermediary resource would then allow duplicates to be created, but of course each one would gets its own id. So for example:

```json
{  
   "data":{  
      "type":"experiment-storages",
      "id":"123",
      "relationships":{  
         "experiment":{  
            "data": {
               "type": "experiments", "id": "1"
            }
         },
         "storage":{  
            "data": {
               "type": "storages", "id": "123"
            }
         }
      }
   }
}
```

The reason you need to implement it like this is because if you're allowing the same experiment/storage link to be inserted multiple times, for a delete request you'd need to know exactly which one in the list the client wants to delete... which they can do by using the id for the specific `experiment-storages` resource.

**Comment by vlavlad** [comment]
@lindyhopchris Thanks for examining. I have additional questions.

1) Is there any way to send the single creating POST request for both experiments and experiment-storages recourses?
2) Does the library support the easy way to implement an intermediary resource lest implement the separated Eloquent for new recourse? It looks like some kind of relationship (hasOne, hasMany)

**Comment by lindyhopchris** [comment]
1. They are planning to add *Operations* to the spec - these will allow you to do multiple things in a single request. However it's still in draft. When it gets added to the spec, I'll add it to this package too as we want to use it too!

2. Easiest way is to have an Eloquent model for the intermediary resource.

**Comment by vlavlad** [comment]
@lindyhopchris I decided to leave the repeated relationship for now. Maybe I will back to this implementation later.

Thank you.
