### ISSUE TITLE
Authorizers for custom routes

### ISSUE THREAD

**Issue by bbprojectnet** [cloudcreativity/laravel-json-api#379]
Hi,

It's possible to custom actions/routes call proper method in authorizer? When we create resource, `create` method is called, so if i had custom action/route `DELETE foo` for `users` resource it should call `foo` method in authorizer, or `deleteFoo` or `fooDelete` or something like this ;)

My code example:
```php
$api
	->resource('users')
	->authorizer('users')
	->only('create', 'read', 'update', 'delete')
	->controller()
	->routes(function ($router) {
		$router->post('foo', 'in');
		$router->delete('foo', 'out');
		$router->patch('foo', 'refresh');
	});
```

if i request `DELETE /api/users/foo` my authorizer call `index` method... it's weird. Why not `delete`? But event that, it hard to write proper logic in one method for delete user and custom delete route.

**Comment by lindyhopchris** [comment]
Hi! The method called on the authorizer is not to do with the HTTP method, but the JSON API defined *action* that is occurring.

So a request to `/api/users` is calling the list-all JSON API action... i.e. accessing all resources. Therefore it ends up in the `index` method of the authorizer.

It's almost impossible for me to add something to the authorizer about custom actions, because I have no idea what applications are doing! Plus the aim of the package is to support the things that the JSON API spec *defines*.

How I would approach this is to just allow the authorizer to pass, then use authorization in each method of your controller for the custom actions. E.g. something like:

```php
public function index($type, $request)
{
    if ($request->isMethod('GET')) {
        // logic for a get request.
    }
}
```

That way, any requests that are not `GET` requests will end up in your controller, where you can do the authorization logic for that specific custom action.

**Comment by lindyhopchris** [comment]
Closing due to inactivty. Refer to details in the above comment if you encounter this issue!
