### ISSUE TITLE
Authorizer on included resources

### ISSUE THREAD

**Issue by dklesev** [cloudcreativity/laravel-json-api#382]
Currently I have to write such code in some Schemas:

```php
            'users' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::SHOW_DATA => isset($includedRelationships['users']),
                self::DATA => function () use ($resource) {

                    if(!Auth::user()->can('view.users'))
                        throw new UnauthorizedException();

                    return $resource->users;
                },
                self::META => function () use ($resource) {
                    return [
                        'count' => $resource->users()->count(),
                    ];
                },
            ],
```

Is there any better way where the authorizers of the included resource can be used?

**Comment by lindyhopchris** [comment]
So we'd approach this via validation... i.e. only allow the `user` include path if a user is signed in. Basically this approach is a lot better than doing it in schemas, because by the time the serialization is occurring, all checking and logic should have been executed... because to do *logic* in the schemas is highly inefficient, particularly when serializing lots of models.

To implement this validation approach, overload the `allowedIncludePaths()` method on your resource's `Validators` class:

```php
    protected function allowedIncludePaths(): AllowedIncludePaths
    {
        if (Auth::check()) {
                $this->allowedIncludePaths[] = 'user';
        }

        return parent::allowedIncludePaths();
    }
```

**Comment by lindyhopchris** [comment]
Closing this as I think the question is answered. Feel free to reopen if you need additional info.
