### ISSUE TITLE
Empty pointer

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#404]
Hi
Maybe i sholdn't use jsonapi for such request, but sometimes i add virtual attributes (e.g. virtualAttribute) amongst normal. For example
```
POST/PATCH
"attributes":{
	"title":"some title",
	"description":"some description",
	"virtualAttribute":"some value",
}
```
And so, because i haven't this attribute amongst eloquent model's attributes, i see 
`{"pointer":"/data"}`
after validation error. 
Maybe add something like `{"pointer":"/data/virtual/virtualAttribute"} `in the Document/ResourceObject::pointer() ? 
So, the problem: can't see which attribute has failed

**Comment by lindyhopchris** [comment]
The pointer refers to the location of the value in the *request* JSON. So if the resource field that produces a validation error does not exist in the *request* JSON, we have to map it to `/data` because that is correct from the request's point of view.

JSON API spec is clear about this:

> `pointer`: a JSON Pointer [RFC6901] to the associated entity in the **request** document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].

So this package will already give a `/data/attributes/virtualAttribute` pointer if:

1. The request contained an attribute member called `virtualAttribute`; AND
2. A Laravel validation rule does not pass for the `virtualAttribute` field. I.e. you'd need something in your validation rules like: `'virtualAttribute' => 'string|min:3'`

Hope that makes sense. Let me know if you feel that doesn't cover what you're describing!
