### ISSUE TITLE
How do I filter endpoints by current logged in user Auth:id?

### ISSUE THREAD

**Issue by cunhar** [cloudcreativity/laravel-json-api#406]
Thank you for your help.

**Comment by rekrios** [comment]
If i understand you correctly...
I made something like this in adapter
```
    protected function filter($query, Collection $filters)
    {
        $query->where('some_table.userId', Auth::user()->id);
    }
```
Maybe there are some more graceful moves

**Comment by cunhar** [comment]
You did understand me correctly :) 

I has seen in the manual to use:  
```
        $this->app->afterResolving(\App\JsonApi\Lapas\Adapter::class, function ($adapter) {
            $adapter->addClosureScope(function ($query) {
                $query->where('id_owner', \Auth::id());
            });
        });
```

in the **AppServiceProvider** file.  But I think your solutions is more obvious for other developers to understand whats going on.

**Comment by rekrios** [comment]
'View' Policy
```
    public function view(User $user, Entity $entityObject)
    {
        return $user->is($entityObject->user);
    }
```

**Comment by lindyhopchris** [comment]
The filter method approach does work, but the limitation is I don't guarantee to call the filter method. 

Scopes is how I do this. The docs specify two ways of attaching them - the closure scopes example you used above, or by writing a class that implements Laravel's `Scope` interface. You can then inject this into your adapter via the constructor. Personally I *always* use that, because as you say it's clearer for a developer when they're looking at the adapter class.
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#scopes

There's a detailed description of the implications of using scopes in that section of the docs. People will receive a `404 Not Found` response if they attempt to access a resource belongs to a different user. This is semantically correct, because if they can *never* access another user's resources then from the API client's perspective the resource doesn't exist (even if it exists in your database).

If you want them to get a `401` or `403` response, you'd need to use Authorizers instead - but for this use case I recommend scopes.
