### ISSUE TITLE
Is it possible to disable the Member ID validation?

### ISSUE THREAD

**Issue by JapSeyz** [cloudcreativity/laravel-json-api#407]
Hi,

I have a specific relationship that I handle manually in the Adapter, to allow both new and existing models to be created/updated in the same request. (in order to save request-count)

However even though the relationship is marked as "Guarded" to prevent any built in relationship handling, it'll still fail with an error 400.

detail: "The member id is required."

Is it possible to remove this validation for specific relationships to handle it manually?

Cheers,

**Comment by lindyhopchris** [comment]
Submitting resource identifiers without an `id` member is against the spec - which is why you're getting that message. The spec says:

> A “resource identifier object” MUST contain type and id members.

As this package is about delivering JSON-API compliant APIs, it's not possible to disable something that is defined by the spec.

If you want to do something that is non-spec compliant, don't register the route for that relationship via the routing helpers provided by this package. Then manually implement the route via normal Laravel route definitions... i.e. handle it yourself.

FYI the spec is aiming to support *Operations* at some point (hopefully soon), which will solve the problem that you're trying to solve by your work-around. I'm definitely planning to add support for that as soon as it is introduced to the spec, because I need to use it too!

**Comment by JapSeyz** [comment]
Alright.

I know it's in the spec, which is why I have a workaround right now, but I'd prefer to keep it as clean as possible.

Let me know if I can be of help when it's introduced to the spec.

Cheers

**Comment by lindyhopchris** [comment]
Ah thanks and no problem! As I say, use the work-around of registering your own relationship route for the mo and hopefully Operations will be great when they get added to the spec!!
