### ISSUE TITLE
Question: conditional attributes

### ISSUE THREAD

**Issue by genyded** [cloudcreativity/laravel-json-api#409]
Could not find this in the docs anywhere, but is there any way to do conditional attributes along the lines of Laravel's resource attributes $this->when?

We know that we can do something like:

```php
public function getAttributes($resource)
{
  return array_filter([
    'shortName' => $resource->short_name,
    'longName' => (Auth::check() && Auth::user()->isAdmin()) ? $resource->long_name : false,
    'banner' => $resource->banner
  ]);
}
```
However that also removes any other attributes with empty values which may not be desired.

We could also do something like:

```php
public function getAttributes($resource)
{
  $arr = [
    'shortName' => $resource->short_name,
    'longName' => $resource->long_name,
    'banner' => $resource->banner
  ];
  if (Auth::check() == false || Auth::user()->is_epa() == false) {
    unset($arr['longName']);
  }
  return $arr;
}
```
... which preserves other attributes with empty values, but is not very clean , especially if you have many conditional attributes. Each would need it's own IF(s). Was hoping for a clean solution or plans to implement one. In real world apps, it's not likely that all users should see all attributes for all api resources  at all times.

**Comment by lindyhopchris** [comment]
So I'm not massively inclined to support conditional attributes. The reason is because it is really inefficient to have to loop over all the attributes to check if they are conditional or not, and filter them out. Doing this when you're serializing lots of resources for a single response is going to take a big hit.

So for the current version of the package, you will need to use the `if statements - though I do agree they are not clean!

For v2, I'll investigate whether I can support conditional attributes - but will only do so if they do not have a performance impact. I can think of potential ways of dealing with them though, but it depends on hooking into the internals of the encoder - which is exceptionally difficult to do because it is provided by another package that has an aversion to such internal modifications!

You might want to take a look at #411 as what you're asking is kind of related to that!

**Comment by lindyhopchris** [comment]
Thanks, will leave open on the `2.0` milestone so I don't forget about it!

**Comment by lindyhopchris** [comment]
Conditional atttributes are fully implemented in the new package `laravel-json-api/laravel` - see https://laraveljsonapi.io
