### ISSUE TITLE
Example of has many Not-Eloquent relation 

### ISSUE THREAD

**Issue by myfbone** [cloudcreativity/laravel-json-api#416]
Can you please add has many Not-Eloquent relation to the demo application? It's a bit difficult to understand how I should implement all this interfaces and abstract classes to make my entities work 😄 
Thanks

**Comment by lindyhopchris** [comment]
Hi! So this is a good idea, but I'll be completely up-front... based on my current workload, I just wouldn't be able to prioritise this. Think it's better to be honest about that rather than promising to do it and not do it for *ages*!

The best example of implementing the adapter classes would be to look through the classes in the `Eloquent` namespace - as they all extend the abstract classes and implement the interface.

Out of interest, what are you using for your entities? Would you be interested in submitting a PR to the demo app to add support for them?

**Comment by myfbone** [comment]
Hello :smiley:
I am using doctrine laravel and entities are just doctrine entities. I trying to make an abstract doctrine adapter based on what I see in your eloquent namespace, so if I do well ofc I will consider PR, but I am not the best programmer so it may take time to make code presentable for contribution :relaxed:
Ultimately I'll try :laughing:

**Comment by lindyhopchris** [comment]
Closing this due to inactivty.

Anyone looking here in the future... the new Eloquent implementation is here:
https://github.com/laravel-json-api/eloquent

I'd happily set up a `laravel-json-api/doctrine` package: but only if someone who uses Doctrine offers to maintain it. I don't use Doctrine in any of my applications, so I need to focus on other priorities.
