### ISSUE TITLE
Filters with "gte" and "lte" definition

### ISSUE THREAD

**Issue by jk100magnys** [cloudcreativity/laravel-json-api#431]
Hello! I've read all docs a couple of times and havent seen any examples of "lte/gte" filters.

For exmaple:
localhost/api/v1/transactions/?filter[id]=+100
or
localhost/api/v1/transactions/?filter[created-at]="+2019-09-29 19:58:57"
or something else.

Could you help me and explain how I could make filters like that?

**Comment by lindyhopchris** [comment]
On the resource adapter there's a `filter()` method and you can put any filter logic in there you want. We don't provide a specific way of doing it because the JSON API spec does not define how filters should be implemented:

> JSON:API is agnostic about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.

So we just provide the ability for the developer to implement their own filter logic in the `filter()` method on the adapter.
