### ISSUE TITLE
[Question] Async using Redis driver.

### ISSUE THREAD

**Issue by umbert-cobiro** [cloudcreativity/laravel-json-api#438]
Hi,

So I've been playing arround with the async jobs and I come across some weird issue. I can run the async jobs without a problem locally when running with the 'sync' driver. But once I deploy and start using redis on my testing environment it does not look like it's pushing elements to the queue. (I'm still trying to get to connect to my test redis env. in order to test this from my local environment, but I have to jump some loops and gates :) )

Is this something that anyone has had problems in the past?

**Comment by lindyhopchris** [comment]
We use async jobs extensively with a Redis queue but haven't had any problems along these lines. It would be worth checking if you have the same problem queuing jobs that aren't queued using the async jobs provided by this package... i.e. determine if this is a problem generally with your application rather than specifically a JSON API package problem.

**Comment by umbert-cobiro** [comment]
Thanks, yes I'm trying to isolate the problem atm, Was just wondering if it wasn't just me. Thanks for the insight.

**Comment by umbert-cobiro** [comment]
Ok, figure it out. It was all in my code and infrastructure. It's working as expected :) Thx again. amazing support for this package
