### ISSUE TITLE
Async Job spitting 500 instead of 303

### ISSUE THREAD

**Issue by umbert-cobiro** [cloudcreativity/laravel-json-api#441]
Hi,

So, this is between a question and a Bug. I'm using the async job with a non-eloquent model but I'm using the `resource_id` on the database to store the item that I'm processing. But is not something that is then queryble. The problem I'm getting is that internally It seems to try resolve the resource read endpoint `resource.read`, this endpoint does not exist dues to me not having the model in the DB.

I can hack it around by changing my adapter and return the information I need, but I don't know if there is an "official way" of doing so. Or if I'm just plain using wrong this feature.

Thanks as usual for ur time and the amazing package :)

**Comment by lindyhopchris** [comment]
Hey!

Sorry for slow reply. I don't think it should matter that the resource isn't an Eloquent model, as long as the resource type/id that is stored on the database is the same JSON API resource type/id that can be used to look up the resource. This is because the type/id is looked up via the JSON API store - that's the thing used internally within the package to retrieve resources.

So really this is a question for you... say your resource was `posts`, presumably `posts` and `1` should be retrievable via your API, even though it isn't an Eloquent model? To do this, you'd need a non-Eloquent adapter for the `posts` resource that is able to lookup `1` (or whatever the ID is that a client would send for that resource).

If it is truely not something that can be retrieved, the solution would be to never store a resource id on the async job.

I.e. only store something in that column that your adapter for that resource can actually look up.

Hope I've explained that ok! Let me know any other follow-up questions!

**Comment by umbert-cobiro** [comment]
Thanks for the reply, yes I did figure it out that was trying to get to the actual resource so it makes 100% sense. 

It was me not make proper use of the package (what a surprise :) )

I ended up using it by modifying my controller and returning the correct code. So I also can use the field to store relevant data.

Thanks again.
