### ISSUE TITLE
[Question] Best practice for guest + auth API routes

### ISSUE THREAD

**Issue by lucianholt97** [cloudcreativity/laravel-json-api#474]
Is there a best practice to have one api for both unauthenticated and authenticated access to specific routes and only include certain fields in the schema when authenticated?
I am trying to prevent creating separate APIs because there would be a lot of duplicate code.
The biggest problem I currently see is that the user object is not exposed on the request when disabling the api:auth middleware. And by adding the middleware I can‘t have unauthenticated access. Otherwise I could check the Authentication within the schema and add fields.

Do you have any best practices or advices for me?
Thanks in advance!

**Comment by lindyhopchris** [comment]
So for different access rights, we just split everything into two APIs. The reason was that there started to be substantial differences between the resource schemas. The more logic you put in your schemas, the slower the encoding gets - so if there's substantial differences I'd recommend splitting the API.

If you don't want to split the API, then this is also possible. Effectively your API would be allow non-authenticated access - so you shouldn't use the `auth` middleware as a result. `Auth::user()`/`Auth::check()` will still work though - so you'd need to manually call that to work out what fields to include in the schema.

Remember that if you're encoding lots of resources, e.g. on `GET /api/posts` endpoint, then the schema could potentially be called 100s of times. The more calls to `Auth::user()` etc you have, the slower the encoding is going to get. So you're best caching the result on the schema the first time you check.
