### ISSUE TITLE
[Question] Best practise for saving resource and its to-many relations

### ISSUE THREAD

**Issue by lucianholt97** [cloudcreativity/laravel-json-api#482]
I would like to ask for advice on how to save a large form which includes a resource and also a to-many relation of this resource. I'm currently working with a recursive function that checks for changes on all (nested) resources and then patches, creates or deletes them (relationships first and then the parent resource).
In general, it works fine. The problem occurs when changing many of the relationships which results in having a lot of requests at the same time when saving. Because Chrome and other browsers only accept 6 requests at a time, this can lead to problems.
Are there any best practices? I don't wont to patch changes incrementally until the user hits the save button.

I'm looking forward to any advice. Thanks in advance!

**Comment by lindyhopchris** [comment]
Yeah it's a good question but it's more a frontend issue than a backend issue.

I specialise in Ember JS on the frontend and this kind of thing is pretty trivial with an excellent package called Ember Concurrency. It effectively allows you to manage asynchronous tasks in the frontend in a really intuitive way, including sequentially structuring asynchronous processes. It's a work of magic, worth checking out the docs even if you're not an Ember developer:
http://ember-concurrency.com/docs/introduction/

If you use Ember, I'd strongly recommend using that - it's one of my favourite things about Ember.

But if you don't then maybe there's other people out there who can suggest managing asynchronous processes in other frontend frameworks? For example I don't know what the equivalent is (if there even is an equivalent) in Vue.js as I don't use Vue.

Ultimately the solution for your scenario is to sequence the promises... i.e. when submit is hit, make some initial saves then once they complete successfully move on to the relationships etc. 

Would be interested to hear what you come up with!

**Comment by cannycookie** [comment]
@lindyhopchris  I'm faced with the same problem and having given this some thought I think it's actually more of a backend issue.

We have a user submitting a survey about a place which has 20 questions.  Our resource is a survey-response which in sql  comprises a survey response parent and many question-answer relations.

If the frontend has to submit one post to create the response followed by 20 other posts for each of the question answers, apart from 20 calls being a bit silly,  it's possible one of them will fail and we will end up with an incomplete result set.

To safely ensure an atomic transaction, we need to submit a single survey response object that can be wrapped in a transaction ensuring that if one fails everything fails.

Dealing with that situation on the frontend is way too complicated, the client can't be - nor should it be responsible for rolling back a load of transactions if one of them failed to commit.

I've slept on this - only for 4 hours, but have concluded that a custom controller is the only way to go in this situation.  As far as the client is concerned the resource should be a complete survey response with all answers.

So that's my reasoning for thinking it's a backend issue caused by normalisation of the data, we end up with efficient storage tables but more complex models that don't necessarily map to our requirements.

**Comment by lindyhopchris** [comment]
@cannycookie good to hear your use case. it's not that this is a frontend or backend issue - it will totally depend on the use case which implementation is appropriate. In your case, the large number of questions to be saved definitely means a backend solution is more appropriate. We find that in our use cases it's totally fine to handle it in the frontend client, but as you point out this won't be the case for every implementation. We do have one use case however where we solved it via the backend as it was more appropriate in that case.

hopefully the operations stuff will get added to the JSON API spec... I'm not sure though as it seems to have been in the pipeline for ages now.

**Comment by cannycookie** [comment]
Thanks for responding @lindyhopchris.  In case anyone has the same issue, this was my solution for a backend controller to handle a multi-relational create.  Don't know if i could incorporate validation in the API to tidy it up a bit, but it works as expected. 

Request data:-
```yaml
{
  "data": {
    "type": "submissions",
    "attributes": {
      "places_id": "Fhs27HIBbEGBG1_d4FKw",
      "answers": [
        {
          "questions_id": "1",
          "question_options_id": "1",
          "response_text": "some users reply"
        },
        {
          "questions_id": "2",
          "question_options_id": "5"
        }
      ]
    }
  }
}
```

```php
    /**
     * Create resource action.
     *
     * @param StoreInterface $store
     * @param CreateResource $request
     * @return Response
     */
    public function create(StoreInterface $store, CreateResource $request)
    {

        DB::beginTransaction();

        try{
            $data = $request->all()['data']['attributes'];
            $data['users_id']=Auth::id();

            if($submission = Submission::create($data))
            {
                //validate each item in the answers array
                $validator = Validator::make($data,[
                    'answers.*.questions_id' => 'required|numeric|exists:questions,id',
                    'answers.*.question_options_id' => 'required|numeric|exists:question_options,id',
                    'answers.*.response_text' =>'nullable'
                ]);

                if ($validator->fails())
                {
                    return $validator->errors();
                }

                $submission->answers()->createMany($data['answers']);
            }

        } catch (\Exception $e)
        {
            DB::rollback();
            throw $e;
        }

        DB::commit();

        return response()->json([
            'message' => __('submission.created'),
            'submission'      => $submission
        ], \Illuminate\Http\Response::HTTP_CREATED);

    }
```
