### ISSUE TITLE
[Question] Integration with laravel sentry package

### ISSUE THREAD

**Issue by yoelpc4** [cloudcreativity/laravel-json-api#509]
Currently I'm integrating [sentry-laravel](https://github.com/getsentry/sentry-laravel) package on my project. This is my sentry reporting lines on Handler@report method

```php
   /**
     * Report or log an exception.
     *
     * @param  Exception  $exception
     * @return void
     * @throws Exception
     */
    public function report(Exception $exception)
    {
        if (\App::environment('production') && \App::bound('sentry') && $this->shouldReport($exception)) {
            \App::make('sentry')->captureException($exception);
        }

        try {
            parent::report($exception);
        } catch (Exception $e) {
            throw $e;
        }
    }
```

However there's setup for `App\Exceptions\Handler` that mention us to register `Neomerx\JsonApi\Exceptions\JsonApiException` at `$dontReport` variable on https://github.com/cloudcreativity/laravel-json-api/blame/master/docs/installation.md#L78-L93 

```php
   /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        JsonApiException::class,
    ];
```

I wonder is this meaning `JsonApiException` on production never catch by sentry?

**Comment by lindyhopchris** [comment]
Hi!

The problem here is that the version of the `neomerx/json-api` package we're on throws those exceptions for a whole variety of reasons. There's no real good way of handling them, as some are meant to be HTTP exceptions and some are things like invalid argument exceptions, but there's no way to distinguish easily.

If you want finer control over whether to report them, you'll need to overload the reporting methods on the exception handler and check the HTTP status on the `JsonApiException` class. There's no other way around it.

The next version I'm working on (whenever I have free time, which is extremely limited at the moment) will solve this as it won't let exceptions from the `neomerx` package bubble up to the exception handler. Upgrading that package helps distinguish so I'll be able to either re-throw them as runtime exceptions or HTTP exceptions, which will resolve this problem.

**Comment by lindyhopchris** [comment]
Closing this as it is dealt with by the new package `laravel-json-api/laravel`, see https://laraveljsonapi.io
