### ISSUE TITLE
Policy for modifyRelationship in create request

### ISSUE THREAD

**Issue by myfbone** [cloudcreativity/laravel-json-api#516]
Hello. I got a question about authorization. I use default authorizer which uses laravel policies. However, I run into an issue. I cannot understand the way I suppose to authorize modifying relationships on resource creation.

Here is an example:
```
POST
{
    "data": {
        "type": "contacts",
        "relationships": {
        	"questionnaire": {
        		"data": {
	        		"type": "questionnaires",
	        		"id": "1"
        		}
        	}
        }
    }
}
```

In this situation authorizer let user to create contact even though questionnaire is not related to user who's sending the request and I have check in questionnaire policy update method. I think that I can probably make separate authorizer for each resource and manually authorize each relationship modifications, but it really decouples authorization from policies. Another thought I had was about modifying create method of default authorizer, parsing all relationships and checking one after one in their related classes. However, I cannot understand how can I convert the relationship name to eloquent model class name. Can you please point me to the best way how can I solve this?

**Comment by geraldokandonga** [comment]
Hello Guys,
I am  also face similar issue but mine is in regards with modifying relationships for example a user has a role and the user has the right to update their own profile, through the policy I have checked and matched the account id with the user  which gives the user the authority to update their profile, since the update method returns true, the user is also able to update any relationship that comes with their profile such as

`{
    "data": {
        "type": "users",
        "attributes": {
            "name": "Immina Andonio",
            "username": "mina",
            "email": "mina@email.com",
            "password": "password",
            "password_confirmation": "password"
        },
        "relationships": {
            "roles": {
                "data": [
                    {
                        "type": "roles",
                        "id": "6"
                    }
                ]
            }
        }
    }
}`

If a user send a post request with the above code to their profile they can actually change their role which might give some users the authority to give themselves admin roles.

The question is how to do I implement authorization to allow users to only update their profile except any relationship unless they have all the right do so?

**Comment by lindyhopchris** [comment]
@geraldokandonga the authorizer has authorization hooks for all the JSON API actions, including modifying relationships. You either need to use the authorizer to reject the request you've shown above. Or altneratively use the validators to validate whether the provided `relationships.roles.data.*.id` is allowed.

**Comment by geraldokandonga** [comment]
@lindyhopchris

Thank you very for the quick reply.

If its not too much to ask would you mind if you can show me how i can implement that? Because i have tried for almost 2 days now and i am not getting better result.

I will really appreciate that, thank you.

**Comment by lindyhopchris** [comment]
@geraldokandonga if you can share with me how you would implement it in a *normal* Laravel controller, then I can show you where to put it when using this package.

**Comment by lindyhopchris** [comment]
Going to close this due to inactivity.
