### ISSUE TITLE
Proposal: Default $fillable property in Adapter

### ISSUE THREAD

**Issue by aprendible** [cloudcreativity/laravel-json-api#562]
# Proposal
When storing data in Laravel, we normally do:

```
$articleData = $request->validate([
    'title' => 'required'...
]);

Article::create($articleData);
```
The ```$articleData``` only contains the validated fields, that way we protect ourselves from mass assignment, and we can can disable that protection in Eloquent to avoid updating ```$fillable``` or ```$guarded``` properties every time we add a new field:

```
namespace App\Models\Article;

class Article extends Model
{
    protected $guarded = [];....
}

```
Now, when doing validation with this awesome package we do:
```
namespace App\JsonApi\Articles;

class Validators extends AbstractValidators
{
    protected function rules($record, $data): array
    {
        return [
            'title' => [...],
            'slug' => [...],
            'content' => [...],
            'authors' => [...],
            'categories' => [...]
        ];
    }
}
```

If we have ```$guarded = []``` disabled in the Article Model, we need to specify the fillable fields in the adapter in order to protect ourselves from mass assignment.
```
namespace App\JsonApi\Articles;

class Adapter extends AbstractAdapter
{
    protected $fillable = ['title', 'slug', 'content', 'categories', 'authors'];
    ...
}
```

As you can see, the keys of the returned array from the rules method is the same as the keys added to the $fillable property
## It would be nice to automatically use the rules keys defined in the ```Validators``` to 'fill' the fillable properties in the ```Adapter``` as default.

If this make sense to you, I would be happy to propose a pull request.

Thanks again for this amazing package...

**Comment by lindyhopchris** [comment]
Thanks for the suggestion. Unfortunately this is a lot more complicated than it seems! The reason why we don't use the validated data at the moment is because the code was actually designed and written before that was a thing in Laravel. At the time we had requests from people to flatten the rules, so that developers didn't have to write rules for `data.attributes.foo` or `data.relationships.bar.data.id`. 

The problem that leaves us with is that the adapter at the moment expects the data in the JSON API format, whereas the validated data is in the flattened format. There would also be other gotchas if we use the validated data - for instance, if there is a relationship called `bar` and you only validated `bar.id` the adapter wouldn't receive `bar.type` which it would need to properly resolve the relationship when filling it.

It would be possible to work around these, but the process isn't simple. My plan had been for the redesigned package to use the validated data, rather than making a substantial breaking change to the current version of the package. I think that's still my preference but feel free to convince me otherwise that the change should be made now!

**Comment by lindyhopchris** [comment]
The new package uses the validated data to fill models, plus has Nova-style fields to define what is fillable and what is read-only. A pre-release of the new package, and documentation, is coming soon.

As such I'm closing this, because it's addressed in the new package and it's not worth me doing a substantial refactor of this existing package. Instead the direction of travel will be to move people to the new package.
