### ISSUE TITLE
CRUD Patch method returning validation errors

### ISSUE THREAD

**Issue by Rezrazi** [cloudcreativity/laravel-json-api#567]
I have the following validator with the following rules
```php
class Validators extends AbstractValidators
{
    // ...
    protected function rules($record, array $data): array
    {
        return [
            'name' => 'required|string|max:100',
            'author' => 'required|string|max:100',
            'secret' => 'required|string|max:100',
        ];
    }
}
```

Sending a POST request with the following body return a `201 Created`
```json
{
    "data": {
        "type": "reports",
        "attributes": {
            "name": "John Doe",
            "author": "Jake Edison",
            "secret": "password_123"
        }
    }
}
```

Sending a PATCH request with the following body returns a `422 Unprocessable Entity`
```json
{
    "data": {
        "type": "reports",
        "id": "1",
        "attributes": {
            "name": "Janet Doe",
            "secret": null
        }
    }
}
```
```json
{
    "errors": [
        {
            "status": "422",
            "title": "Unprocessable Entity",
            "detail": "The secret field is required.",
            "source": {
                "pointer": "/data/attributes/secret"
            }
        }
    ]
}
```

Removing the `required` rule for `secret` or changing it to `nullable` and sending the request again returns a `200`, even though there are two required rules for the `name` and `author` fields and only providing one of these two fields in the body, it does not throw any errors and the entity gets patched.

**Comment by lindyhopchris** [comment]
Hi! So the spec says this about update requests:

> If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values.
https://jsonapi.org/format/#crud-updating-resource-attributes

As such, if any values are not provided for the update request, the validator is given the current values for the missing attributes. We use the Schema's `getAttributes()` method to work out the current values. That is why the `required` rules are passing for the update request even though the `name` and `author` fields are not provided - because the data given to the validator has the current values.

That's explained in this package's documentation here:
https://laravel-json-api.readthedocs.io/en/latest/basics/validators/#updating-resources

I think that answers your query, but let me know if it's not fully answered!

**Comment by Rezrazi** [comment]
That does indeed answer my question, thank you.

However, if for some reason I do not want an attribute to show up in a resource, but still have it in the `getAttributes()` to get the PATCH request to pass, how can I achieve that ? (for instance a secret field that needs to be present in the method but not necessarily show up in the resource attributes)

**Comment by lindyhopchris** [comment]
Sorry, somehow missed your reply!

The `existingAttributes($record)` method on the `Validators` class is used to work out what the existing attributes are for a `PATCH` request. It's `protected`, so you can overload it if you need to do something custom. E.g.

```
protected function existingAttributes($record): iterable
{
    $attrs = parent::existingAttributes($record);
    $attrs['secret'] = 'blah';
    return $attrs;
}
```

However, I suspect that the better way of dealing with this is to actually adjust your validation rules. For a `PATCH`, you probably either don't expect the `secret`, or you only expect to validate it if it is present. If the latter, the `filled` rule will work for you. So maybe your `rules` method should be this:

```php
class Validators extends AbstractValidators
{
    // ...
    protected function rules($record, array $data): array
    {
        return [
            'name' => 'required|string|max:100',
            'author' => 'required|string|max:100',
            'secret' => [
                $record ? 'filled' : 'required', 
                'string', 
                'max:100',
            ],
        ];
    }
}
```

That works because `$record` is `null` for a `POST` request, and is the model for a `PATCH`.
