### ISSUE TITLE
Call to undefined method CloudCreativity\LaravelJsonApi\Routing\RelationshipRegistration::uri()

### ISSUE THREAD

**Issue by osteel** [cloudcreativity/laravel-json-api#573]
Hi,

[The documentation mentions a `uri` method](https://laravel-json-api.readthedocs.io/en/latest/basics/routing/#relationship-routes) that we can use to customise the URI fragment for any given relationship, but that method doesn't seem to exist.

Maybe it's been removed at some point – is there another way to achieve this?

This actually brings up a side question, which is about naming resources. Some time ago the JSON:API specification dropped the use of hyphens in favour of [camel case](https://jsonapi.org/recommendations/#naming) to name "members", without specifying what those members are.

I apply this to attributes, and for consistency, I've also started to do the same for resource names (e.g. `tenancyAgreements` instead of `tenancy-agreements`). Is that a correct way of interpreting the JSON:API recommendation, in your opinion?

Cheers,

Yannick

**Comment by osteel** [comment]
I've just made a quick test to customise the URI fragment of a [resource route](https://laravel-json-api.readthedocs.io/en/latest/basics/routing/#resource-routes) this time, and the `uri` method doesn't seem to exist either:

```php
Call to undefined method CloudCreativity\LaravelJsonApi\Routing\ResourceRegistration::uri()
```

**Comment by osteel** [comment]
Never mind – I should have checked the latest releases before posting. I've now upgraded from `3.0.0` to `3.2.0` and the methods are back.

Sorry for the trouble!

Cheers

Yannick

**Comment by lindyhopchris** [comment]
Aha, no problem! Yeah these have only just been added. Glad you figured out that an upgrade was required.

**Comment by osteel** [comment]
@lindyhopchris ;)

Actually if you've got a minute, I'm still struggling a bit with naming resources, and maybe you've got an opinion as you obviously work a lot with JSON:API.

I'm basically unsure how to format multi-words resource names based on the context, such as:

* resource name itself;
* URI fragment;
* `include` query parameter;
* included relationship in the response;
* probably others.

Let's take tenancy agreements as an example again. If we apply JSON:API's recommendation of using camel case for _members_ to resources, the corresponding resource should probably be named `tenancyAgreements`. The same name can then be used for the resource included as a relationship in HTTP responses, as a list (`tenancyAgreements`) or as a single item (`tenancyAgreement`).

The issue with this is when featuring the resource as part of an URL, e.g. as the targeted resource or as a value for an `include` query parameter. Sure most servers support it now, but I'd rather not rely on the URL being case-sensitive.

Would you make that value `tenancy-agreements` or `tenancy-agreement`, then, even if it's inconsistent with the resource name otherwise? Or do you always name resources in _kebab case_ (with hyphens) no matter what?

Is this something you have rules for at all?

I know this is not strictly related to this package, by the way, so no worries if you can't be arsed replying.

Cheers,

Yannick

**Comment by osteel** [comment]
I've just realised that, of course, the issue is the same with camel case attributes, used as values for `filter` or `sort` query parameters, for instance. Should these be case-sensitive, then?

It's the first time I implement an API following the JSON:API spec since they advocate using camel case instead of kebab case – I must admit this confuses me a bit :)

**Comment by lindyhopchris** [comment]
The resource *type* isn't a member name. Member names refer to the object keys in JSON.

My personal preference is to dash-case and pluralize resource types - i.e. `tenancy-agreements`. That means when it's in the URI it is also dash-case.

The camel-case for member names works well as it is easy to refer to in Javascript. I.e. you can do `resource.memberName` rather than having to do `resource['member-name']`.

Relationships are the only member names that appear as URI fragments. In these cases I prefer to dash-case the relationship, because camel-case seems strange in URIs which are typically regarded as case-insensitive. So although the member name of a relationship in the JSON document is `memberName`, I'd use the following URI: `/api/tenancy-agreements/member-name` and `/api/tenancy-agreements/relationships/member-name`.

As for query parameters, I'm more comfortable with those being case-sensitive, as the value is just a string value in the query parameter. So when a query parameter refers to a member name, i.e. in the `include` or `fields` query param, I'd expect it to be the same as the member name i.e. camel case:

`GET /api/tenancy-agreements?include=memberName`

I.e. the member name in that URI isn't actaully part of the URI - it's a string query parameter value, so think it's fine to be camel-cased.

Anyway, that's my thoughts!

**Comment by osteel** [comment]
I see. The URI fragments vs query parameters dichotomy makes sense, I think. I like your approach, even if it introduces a little bit of inconsistency; besides, I agree that camel-cased URI fragments feels... wrong.

For reference, there is an [issue about this in the specification's repository](https://github.com/json-api/json-api/issues/1431). The author settled on a full camel-case solution, apparently. Ultimately, it's down to the implementer to make a choice and stick to it, but I think the correlation between member/type names and URLs which is encouraged by the specification inevitably raises these questions at some point.

Anyway, thanks for taking the time!

**Comment by ben221199** [comment]
There are 3 name types:
 - The resource type in the `type` property.
 - The URI to access the resource type.
 - The relation name of a resource that is related to another resource.

When having a resource that represents a user, I would do this:

### Resource type
**Example:** `user` (or `laravel_user` / `github_user`)
**Name Suggestion** singular (because it is only one resource)

If you manage multiple websites with each a own user system, you want to distingish the two, so you could add the name of the website in the resource type. For example, I have a website that sells domains in one product (Domains) and use domains with other properties in another product (Enterprise). Therefore, I don't have just one resource called `domain`, but one resource called `domains_domain` for my product Domains and one product called `enterprise_domain` for my product Enterprise.

### URI
**Example:** `/v1/users` (or `/laravel/v1/users` / `/github/v1/users`)
**Name Suggestion** plural (because you can access multiple resources on this endpoint)

Same as above, choose `/v1/users` if you only have one type of users and choose the Laravel/Github one when having multiple sites or products with each there own user type.

**NOTE:** Please version your API. For example, use `/v1` as used above. If you change something on `/v1` that will not work on product software that is already released, than it will break. So, then change it on `/v2`.

### Relationships
**Example:**
 - `partner` & `/v1/users/<id>/partner` (or `/laravel/v1/users/<id>/partner` / `/github/v1/users/<id>/partner`)
 - `partners` & `/v1/users/<id>/partners` (or `/laravel/v1/users/<id>/partners` / `/github/v1/users/<id>/partners`)
 - `book` & `/v1/users/<id>/book` (or `/laravel/v1/users/<id>/book` / `/github/v1/users/<id>/book`)
 - `books` & `/v1/users/<id>/books` (or `/laravel/v1/users/<id>/books` / `/github/v1/users/<id>/books`)
**Name Suggestion** singular (when it is a hasOne relationship) / plural (when it is a hasMany relationship)

Relationships are fun, because they don't need to be the same as your resource type or self-URI. For example `partner` and `partners` in the example is a relationship that will give the partner or partners (why would you have more, but okay) of a specific user. And this partner or partners are also of the type `user` (or `laravel_user` / `github_user`). But as you see, the name of the relationship is not the same. You can actually name it as you want. For example, if you also want to show the friend / friends of a user, and that friend / friends are also of the type `user` (or `laravel_user` / `github_user`), then that is fine. And if you want a relationship with the type `book`, go ahead.

**Comment by osteel** [comment]
@ben221199 thanks for your input!
