### ISSUE TITLE
i cant get the correct image url from the response

### ISSUE THREAD

**Issue by pro-cms** [cloudcreativity/laravel-json-api#591]
In the database i have image file stored as :     
**simulizis\February2021\1MNob4erSKcquglyfPTm.png**
now when i retrive from the database using API and in the schema i specified as 

**public function getAttributes($resource)
    {
        return [
            'simulizi_title'=>$resource->simulizi_title,
            'simulizi_description'=>$resource->simulizi_description,
            'simulizi_thumb'=>$resource->simulizi_thumb,
            'created-at' => $resource->created_at->toAtomString(),
            'updated-at' => $resource->updated_at->toAtomString(),
        ];
    }**

Now the request doesnot return the correct image url path, here is the response using postman

**attributes": {
                "simulizi_title": "dfdfdfd",
                "simulizi_description": "dfdfd",
                "simulizi_thumb": "simulizis\\\February2021\\\1MNob4erSKcquglyfPTm.png",
                "created-at": "2021-02-27T21:26:28+00:00",
                "updated-at": "2021-02-27T21:34:29+00:00"
            },**

i would like it to return response as 

**storage/stories/February2021/4CAv5ZVqIj4RR9pXpp3v.png**

so that i can easly fetch the image url

**Comment by lindyhopchris** [comment]
This doesn't look like anything to do with this package. By doing `$resource->simulizi_thumb` you are returning the value fro your model. If your model has the value of `simulizis\February2021\1MNob4erSKcquglyfPTm.png` then the `\` will be escaped in the JSON which is why you're seeing the double slashes. Decoding the JSON would take care of that.

I'm a little bit confused as to why your image URL has `\` instead of `/`, but that's down to whatever  you're doing to store the value in your database and doesn't relate to this package.
