### ISSUE TITLE
Use another field different than {resource_id} in GET/PATCH/DELETE routes 

### ISSUE THREAD

**Issue by gigo6000** [cloudcreativity/laravel-json-api#65]
Hi, by default routes use the resource id, for example: GET /posts/{resource_id}, but is it possible to use a different a field for example an slug? /posts/{slug}, not sure if this against the jsonapi.org but so far I haven't found anything against it in the spec. Thanks

**Comment by lindyhopchris** [comment]
No, there's nothing stopping you using whatever you want for the identifier... as long as it identifies a unique resource. The routing doesn't need to change - the logic of how you translate the `resource_id` route parameter to specific resource is handled by the resource's `Adapter` class.

For example, if you were using the `slug` property on an Eloquent model rather than the model's primary key, just set this property on your adapter:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Store/EloquentAdapter.php#L52-L59

You will also need to update your `Schema` so that it returns the slug as the resource id when encoding the resources, using this property:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Schema/EloquentSchema.php#L35-L42

**Comment by gigo6000** [comment]
Sorry for the late reply, this seems to be working fine, thanks!
