### ISSUE TITLE
Hydrating hasMany with correct ID

### ISSUE THREAD

**Issue by danherd** [cloudcreativity/laravel-json-api#91]
I am using UUIDs in a 'supplemental' manner - i.e. they are what is output and accepted by by the API, but standard auto-incrementing integers are used in the database joins.

hasOne relationships seem to populate fine when a UUID is supplied, for example:

```
{
    "data": {
        "type": "locums",
        "attributes": {
            "name": "Test Account",
            "email": "test@test.com",
            "password": "abcd1234",
            "password-confirmation": "abcd1234"
        },
        "relationships": {
        	"country": {
        		"data": { "type": "countries", "id": "GB" }
        	},
        	"region": {
        		"data": { "type": "regions", "id": "6F0073EC-3C98-4831-9595-890DF79E6E7D" }
        	},
        	"locum-type": {
        		"data": { "type": "locum-types", "id": "14C179EA-363F-4585-8879-6111CD162D62" }
        	}
        }
    }
}
```

In the instance above, the 'region_id' and 'locum_type_id' fields in the 'locums' table is correctly populated with the integers instead of the supplied UUIDs.

However, attempting to populate a hasMany relationship (employees below):

```
{
    "data": {
        "type": "practices",
        "attributes": {
            "name": "Test Veterinary Practice"
        },
        "relationships": {
            "country": {
                "data": { "type": "countries", "id": "GB" }
            },
            "employees": {
            	"data": [
                	{ "type": "employees", "id": "DDF08296-995A-42B5-847B-FD55E8F7C813" }
            	]
            }
        }
    }
}
```

doesn't work, as it tries to populate the pivot table ('employee_practice') with the UUID instead of the integer.

Is there something else I need to configure in any of the API code to make this work properly? I'm willing to supply any other information needed to get this working.

Cheers.

**Comment by lindyhopchris** [comment]
Hi. Yes, this seems to be a problem with the different ways its hydrating relationships. For has-one, it is retrieving the actual related model from the database and then calling `associate` on the relationship. However for has-many, it's just reading the IDs out of the JSON API request and calling `sync`.

It makes more sense to retrieve all of the models and pass those into `sync`, because then the model key will get used properly.

I'm planning on refactoring the hydrators at some point for v1.0, but can probably fix this via a bug fix now. I'll see if I can get to it this week but I am completely overrun with work at the moment.

As a quick note to myself, this is the line that needs changing:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Hydrator/EloquentHydrator.php#L344

**Comment by lindyhopchris** [comment]
Yep, that would work as a temp fix

**Comment by danherd** [comment]
FYI - here's what I've gone with:

```
    protected function syncHasMany($resourceKey, RelationshipInterface $relationship, Model $model)
    {
        $relation = $this->getRelation($resourceKey, $model);

        if (!$relation instanceof BelongsToMany) {
            return false;
        }

        foreach ($relationship->getIdentifiers() as $identifier) {
             $relation->attach($this->findRelated($identifier));
        };

        return true;
    }
```

**Comment by lindyhopchris** [comment]
Yeah, that's basically what I'm going to have to change it to. You might want to use `sync` though rather than `attach`, as you need to detach any already attached models that are not in the list of identifiers. 

I need to add an interface method to the store so that you can convert the ids in a single query rather than looping like that. But will have to do that in a future release as it'll be breaking as I'll need to change the interfaces.

**Comment by lindyhopchris** [comment]
Closing this as it is implemented on the `1.x-dev` branch.
